// Top 21 Indian entrance exams — metadata seed.
// Run: npx tsx seed/exams/index.ts
//
// This seeds the Exam table only. Subjects/topics come from per-exam
// syllabus files (e.g. ssc-cgl-syllabus.ts). Questions come from per-exam
// question seed files. We do this in three layers so each can be iterated
// independently as content matures.

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const examsSeed = [
  {
    code: "SSC_CGL",
    name: "SSC Combined Graduate Level (Tier 1)",
    shortName: "SSC CGL",
    category: "GOVT_JOBS" as const,
    description:
      "Staff Selection Commission Combined Graduate Level Exam — Tier 1 is a 60-minute objective test with 100 questions across Reasoning, GK, Quant, and English.",
    durationMin: 60,
    totalQuestions: 100,
    totalMarks: 200,
    marksPerQ: 2,
    negativeMark: 0.5,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 3_000_000,
  },
  {
    code: "RRB_NTPC",
    name: "Railway Recruitment Board NTPC",
    shortName: "RRB NTPC",
    category: "GOVT_JOBS" as const,
    description:
      "RRB Non-Technical Popular Categories. Tier 1 (CBT) has 100 questions in 90 minutes covering Math, Reasoning, and General Awareness.",
    durationMin: 90,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 1 / 3,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 12_500_000,
  },
  {
    code: "IBPS_PO",
    name: "IBPS Probationary Officer (Prelims)",
    shortName: "IBPS PO",
    category: "BANKING" as const,
    description:
      "Institute of Banking Personnel Selection PO Prelims — 100 questions in 60 minutes on Reasoning, Quant, and English.",
    durationMin: 60,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 1_500_000,
  },
  {
    code: "NEET_UG",
    name: "National Eligibility cum Entrance Test (UG)",
    shortName: "NEET UG",
    category: "MEDICAL" as const,
    description:
      "Single national medical entrance test. 200 questions (180 to attempt) in 200 minutes covering Physics, Chemistry, and Biology.",
    durationMin: 200,
    totalQuestions: 200,
    totalMarks: 720,
    marksPerQ: 4,
    negativeMark: 1,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 2_400_000,
  },
  {
    code: "JEE_MAIN",
    name: "Joint Entrance Examination — Main",
    shortName: "JEE Main",
    category: "ENGINEERING" as const,
    description:
      "Engineering entrance test. 90 questions (75 to attempt) in 180 minutes across Physics, Chemistry, and Mathematics.",
    durationMin: 180,
    totalQuestions: 75,
    totalMarks: 300,
    marksPerQ: 4,
    negativeMark: 1,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 1_400_000,
  },
  {
    code: "UPSC_PRELIMS",
    name: "UPSC Civil Services Examination — Prelims",
    shortName: "UPSC Prelims",
    category: "CIVIL_SERVICES" as const,
    description:
      "UPSC CSE Prelims. Two papers: GS Paper 1 (100 Qs, 200 marks, 2 hours) and CSAT (80 Qs, 200 marks, qualifying).",
    durationMin: 120,
    totalQuestions: 100,
    totalMarks: 200,
    marksPerQ: 2,
    negativeMark: 2 / 3,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 1_100_000,
  },
  {
    code: "CUET_UG",
    name: "Common University Entrance Test (UG)",
    shortName: "CUET UG",
    category: "UNIVERSITY" as const,
    description:
      "Common entrance for central universities. CBT format with domain subjects, language, and general test sections.",
    durationMin: 195,
    totalQuestions: 175,
    totalMarks: 700,
    marksPerQ: 5,
    negativeMark: 1,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 1_400_000,
  },
  {
    code: "CTET",
    name: "Central Teacher Eligibility Test",
    shortName: "CTET",
    category: "TEACHING" as const,
    description:
      "Eligibility test for teaching positions in central government schools. Paper I (Class 1–5) and Paper II (Class 6–8).",
    durationMin: 150,
    totalQuestions: 150,
    totalMarks: 150,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 3_000_000,
  },
  {
    code: "GATE_CSE",
    name: "Graduate Aptitude Test in Engineering — Computer Science",
    shortName: "GATE CSE",
    category: "ENGINEERING" as const,
    description:
      "Postgraduate engineering admission + PSU recruitment. CSE paper has 65 questions in 180 minutes covering core CS topics + Aptitude + Engineering Math.",
    durationMin: 180,
    totalQuestions: 65,
    totalMarks: 100,
    marksPerQ: 1.5,
    negativeMark: 1 / 3,
    languages: ["EN"] as const,
    candidatesPerYear: 100_000,
  },
  {
    code: "CAT",
    name: "Common Admission Test",
    shortName: "CAT",
    category: "MBA" as const,
    description:
      "MBA entrance for IIMs and other top business schools. 66 questions in 120 minutes across VARC, DILR, and Quant.",
    durationMin: 120,
    totalQuestions: 66,
    totalMarks: 198,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN"] as const,
    candidatesPerYear: 350_000,
  },
  // ── SSC family (additions) ──────────────────────────────────────────────
  {
    code: "SSC_CHSL",
    name: "SSC Combined Higher Secondary Level (Tier 1)",
    shortName: "SSC CHSL",
    category: "GOVT_JOBS" as const,
    description:
      "SSC CHSL Tier 1 — 60-minute objective test with 100 questions (English, Reasoning, Quant, GA) for 12th-pass clerical posts.",
    durationMin: 60,
    totalQuestions: 100,
    totalMarks: 200,
    marksPerQ: 2,
    negativeMark: 0.5,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 3_500_000,
  },
  {
    code: "SSC_MTS",
    name: "SSC Multi Tasking Staff (Paper 1)",
    shortName: "SSC MTS",
    category: "GOVT_JOBS" as const,
    description:
      "SSC MTS Paper 1 — 90-minute test for Group C non-gazetted posts. Two sessions: Reasoning + Numerical (45 min), GA + English (45 min).",
    durationMin: 90,
    totalQuestions: 90,
    totalMarks: 270,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 5_000_000,
  },
  {
    code: "SSC_GD",
    name: "SSC General Duty Constable",
    shortName: "SSC GD",
    category: "GOVT_JOBS" as const,
    description:
      "SSC GD Constable CBT — 60-minute test with 80 questions for CAPF/Assam Rifles/SSF constable posts. Reasoning, GK, Math, English/Hindi.",
    durationMin: 60,
    totalQuestions: 80,
    totalMarks: 160,
    marksPerQ: 2,
    negativeMark: 0.5,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 5_500_000,
  },
  // ── RRB family (additions) ──────────────────────────────────────────────
  {
    code: "RRB_GROUP_D",
    name: "Railway Group D (Level 1)",
    shortName: "RRB Group D",
    category: "GOVT_JOBS" as const,
    description:
      "RRB Group D CBT — 90-minute test with 100 questions (Math, Reasoning, General Science, GA) for Level 1 posts in Indian Railways.",
    durationMin: 90,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 1 / 3,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 11_000_000,
  },
  {
    code: "RRB_ALP",
    name: "Railway Assistant Loco Pilot (CBT-1)",
    shortName: "RRB ALP",
    category: "GOVT_JOBS" as const,
    description:
      "RRB ALP first-stage CBT — 60-minute screening test with 75 questions (Math, Reasoning, General Science, GA). Qualifying for Stage 2.",
    durationMin: 60,
    totalQuestions: 75,
    totalMarks: 75,
    marksPerQ: 1,
    negativeMark: 1 / 3,
    languages: ["EN", "HI", "TE", "TA", "KN", "ML", "MR", "BN", "GU", "PA"] as const,
    candidatesPerYear: 2_000_000,
  },
  // ── Engineering (additions) ─────────────────────────────────────────────
  {
    code: "JEE_ADVANCED",
    name: "Joint Entrance Examination — Advanced",
    shortName: "JEE Advanced",
    category: "ENGINEERING" as const,
    description:
      "Two-paper test for IIT admission. Each paper is 3 hours covering Physics, Chemistry, Mathematics with mixed question patterns (single, multiple-correct, integer, matrix-match).",
    durationMin: 360,
    totalQuestions: 108,
    totalMarks: 360,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 250_000,
  },
  // ── Banking (additions) ─────────────────────────────────────────────────
  {
    code: "IBPS_CLERK",
    name: "IBPS Clerk (Prelims)",
    shortName: "IBPS Clerk",
    category: "BANKING" as const,
    description:
      "IBPS Clerk Prelims — 60-minute test with 100 questions (English, Quant, Reasoning) for clerical posts in public sector banks.",
    durationMin: 60,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 1_800_000,
  },
  {
    code: "SBI_PO",
    name: "SBI Probationary Officer (Prelims)",
    shortName: "SBI PO",
    category: "BANKING" as const,
    description:
      "SBI PO Prelims — 60-minute test with 100 questions (English, Quant, Reasoning) for officer posts in State Bank of India.",
    durationMin: 60,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 2_500_000,
  },
  {
    code: "SBI_CLERK",
    name: "SBI Clerk (Prelims)",
    shortName: "SBI Clerk",
    category: "BANKING" as const,
    description:
      "SBI Clerk Prelims — 60-minute test with 100 questions (English, Quant, Reasoning) for Junior Associate (Customer Support) posts in SBI.",
    durationMin: 60,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 2_000_000,
  },
  // ── Defence (additions) ─────────────────────────────────────────────────
  {
    code: "CDS",
    name: "Combined Defence Services Examination",
    shortName: "CDS",
    category: "GOVT_JOBS" as const,
    description:
      "UPSC CDS — three papers (English, GK, Elementary Maths) for entry to Indian Military Academy, Naval Academy, Air Force Academy, and Officers Training Academy.",
    durationMin: 360,
    totalQuestions: 300,
    totalMarks: 300,
    marksPerQ: 1,
    negativeMark: 1 / 3,
    languages: ["EN"] as const,
    candidatesPerYear: 400_000,
  },
  {
    code: "NDA",
    name: "National Defence Academy & Naval Academy Examination",
    shortName: "NDA",
    category: "GOVT_JOBS" as const,
    description:
      "UPSC NDA — two papers: Mathematics (300 marks, 2.5 hrs) and General Ability Test (English + GK, 600 marks, 2.5 hrs) for entry to NDA Khadakwasla.",
    durationMin: 300,
    totalQuestions: 270,
    totalMarks: 900,
    marksPerQ: 4,
    negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 600_000,
  },
  // ── Olympiads — HBCSE 5-stage chain (Stage-1) ──────────────────────────
  {
    code: "IOQM",
    name: "Indian Olympiad Qualifier in Mathematics",
    shortName: "IOQM",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE Stage-1 for the Indian math olympiad chain (RMO → INMO → IMOTC → IMO). 30 questions in 3 hours, integer answers 00–99, no calculus.",
    durationMin: 180,
    totalQuestions: 30,
    totalMarks: 100,
    marksPerQ: 5,
    negativeMark: 0,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 70_000,
  },
  {
    code: "NSEP",
    name: "National Standard Examination in Physics",
    shortName: "NSEP",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE/IAPT Stage-1 physics olympiad. 80 MCQs (60 single-correct + 20 multi-correct) in 3 hours covering Class 11+12 physics and olympiad-style problem solving.",
    durationMin: 180,
    totalQuestions: 80,
    totalMarks: 216,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 25_000,
  },
  {
    code: "NSEC",
    name: "National Standard Examination in Chemistry",
    shortName: "NSEC",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE/IAPT Stage-1 chemistry olympiad. 80 MCQs in 3 hours — physical, inorganic, and organic chemistry at Class 11+12 level with olympiad-style depth.",
    durationMin: 180,
    totalQuestions: 80,
    totalMarks: 216,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 20_000,
  },
  {
    code: "NSEB",
    name: "National Standard Examination in Biology",
    shortName: "NSEB",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE/IAPT Stage-1 biology olympiad. 80 MCQs in 3 hours covering cell biology, genetics, plant & animal physiology, ecology, and evolution.",
    durationMin: 180,
    totalQuestions: 80,
    totalMarks: 216,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 18_000,
  },
  {
    code: "NSEA",
    name: "National Standard Examination in Astronomy",
    shortName: "NSEA",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE/IAPT Stage-1 astronomy olympiad. 80 MCQs in 3 hours combining Class 11+12 physics & math with celestial mechanics, spherical trigonometry, and observational astronomy.",
    durationMin: 180,
    totalQuestions: 80,
    totalMarks: 216,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN"] as const,
    candidatesPerYear: 8_000,
  },
  {
    code: "NSEJS",
    name: "National Standard Examination in Junior Science",
    shortName: "NSEJS",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE/IAPT Stage-1 junior science olympiad for Class 8–10 students. 80 MCQs in 2 hours integrating physics, chemistry, biology, and mathematics at Class 8–10 NCERT level.",
    durationMin: 120,
    totalQuestions: 80,
    totalMarks: 216,
    marksPerQ: 3,
    negativeMark: 1,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 50_000,
  },
  // ── Olympiads — SOF (Science Olympiad Foundation) ──────────────────────
  {
    code: "SOF_NSO",
    name: "SOF National Science Olympiad",
    shortName: "SOF NSO",
    category: "OLYMPIAD" as const,
    description:
      "School-level science olympiad conducted by SOF. 35 questions for Class 1–4, 50 questions for Class 5–12 in Logical Reasoning, Science, and Achievers Section.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 4_000_000,
  },
  {
    code: "SOF_IMO",
    name: "SOF International Mathematics Olympiad",
    shortName: "SOF IMO",
    category: "OLYMPIAD" as const,
    description:
      "SOF math olympiad for school students. 35–50 questions across Logical Reasoning, Mathematical Reasoning, Everyday Mathematics, and an Achievers Section.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 3_500_000,
  },
  {
    code: "SOF_IEO",
    name: "SOF International English Olympiad",
    shortName: "SOF IEO",
    category: "OLYMPIAD" as const,
    description:
      "SOF English olympiad. Word & Structure Knowledge, Reading, Spoken & Written Expression, Achievers Section. Class 1–12.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 1_800_000,
  },
  {
    code: "SOF_IGKO",
    name: "SOF International General Knowledge Olympiad",
    shortName: "SOF IGKO",
    category: "OLYMPIAD" as const,
    description:
      "SOF GK olympiad covering general awareness, current affairs, life skills, and an Achievers Section. Class 1–10.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 1_200_000,
  },
  {
    code: "SOF_ICO",
    name: "SOF International Commerce Olympiad",
    shortName: "SOF ICO",
    category: "OLYMPIAD" as const,
    description:
      "SOF commerce olympiad for Class 11–12 commerce students. Reasoning, Commerce (Business Studies + Accountancy), Economics, and Achievers Section.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 200_000,
  },
  {
    code: "SOF_IHO",
    name: "SOF International Hindi Olympiad",
    shortName: "SOF IHO",
    category: "OLYMPIAD" as const,
    description:
      "SOF Hindi olympiad. Hindi Vyakaran, Reading, Expression, Achievers Section. Class 1–10.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["HI"] as const,
    candidatesPerYear: 600_000,
  },
  // ── Olympiads — Silverzone Foundation ──────────────────────────────────
  {
    code: "SZF_IOM",
    name: "Silverzone International Olympiad of Mathematics",
    shortName: "SZF IOM",
    category: "OLYMPIAD" as const,
    description:
      "Silverzone math olympiad for school students. Math content, reasoning, and an Achievers Section. Heavier emphasis on visual/spatial reasoning than SOF.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 700_000,
  },
  {
    code: "SZF_IOS",
    name: "Silverzone International Olympiad of Science",
    shortName: "SZF IOS",
    category: "OLYMPIAD" as const,
    description:
      "Silverzone integrated PCB olympiad for school students with reasoning and an Achievers Section.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 600_000,
  },
  {
    code: "SZF_IOEL",
    name: "Silverzone International Olympiad of English Language",
    shortName: "SZF IOEL",
    category: "OLYMPIAD" as const,
    description:
      "Silverzone English language olympiad. Grammar, vocabulary, comprehension, speech & pronunciation, achievers section.",
    durationMin: 60,
    totalQuestions: 50,
    totalMarks: 60,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 400_000,
  },
  // ── Olympiads — Unified Council ────────────────────────────────────────
  {
    code: "NSTSE",
    name: "National Level Science Talent Search Examination",
    shortName: "NSTSE",
    category: "OLYMPIAD" as const,
    description:
      "Unified Council's diagnostic talent test for Class 2–12. Math, Physics, Chemistry, Biology, and General Reasoning — application-heavy, not memorization-based.",
    durationMin: 90,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 500_000,
  },
  // ── Olympiads — Computing & Linguistics (HBCSE/IARCS) ──────────────────
  {
    code: "ZIO",
    name: "Zonal Informatics Olympiad",
    shortName: "ZIO",
    category: "OLYMPIAD" as const,
    description:
      "IARCS Stage-1 informatics olympiad. Pen-and-paper paper on algorithmic problem-solving — no programming language knowledge required. 4 problems in 3 hours.",
    durationMin: 180,
    totalQuestions: 4,
    totalMarks: 100,
    marksPerQ: 25,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 5_000,
  },
  {
    code: "PRIL",
    name: "Panini Linguistics Olympiad",
    shortName: "PRIL",
    category: "OLYMPIAD" as const,
    description:
      "HBCSE Stage-1 linguistics olympiad. Self-contained linguistic puzzles in unfamiliar languages — no prior linguistic knowledge needed. Solved by pattern recognition.",
    durationMin: 180,
    totalQuestions: 6,
    totalMarks: 100,
    marksPerQ: 17,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 3_000,
  },

  // ── BATCH 6 SEED — niche entrances + previously-uncovered banking ──

  {
    code: "IBPS_RRB",
    name: "IBPS Regional Rural Bank (Officer Scale + Office Assistant)",
    shortName: "IBPS RRB",
    category: "BANKING" as const,
    description:
      "Common Recruitment Process for Officer Scale I/II/III and Office Assistant posts at 43 Regional Rural Banks across India. Three-tier process: Prelims → Mains → Interview (Scale II/III directly to single CBT).",
    durationMin: 45,
    totalQuestions: 80,
    totalMarks: 80,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN", "HI", "BN", "GU", "KN", "ML", "MR", "PA", "TA", "TE"] as const,
    candidatesPerYear: 1_500_000,
  },
  {
    code: "RBI_GRADE_B",
    name: "RBI Officer in Grade B (DR — General + DEPR + DSIM)",
    shortName: "RBI Grade B",
    category: "BANKING" as const,
    description:
      "Reserve Bank of India officer-cadre recruitment. Phase 1 (objective) + Phase 2 (objective + descriptive papers in Economic & Social Issues, English Writing, Finance & Management) + Interview. Three streams: General, DEPR (Economics), DSIM (Statistics).",
    durationMin: 120,
    totalQuestions: 200,
    totalMarks: 200,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN"] as const,
    candidatesPerYear: 300_000,
  },
  {
    code: "NATA",
    name: "National Aptitude Test in Architecture",
    shortName: "NATA",
    category: "UNIVERSITY" as const,
    description:
      "Council of Architecture's qualifying test for admission to B.Arch programmes across India. Two parts: aesthetic sensitivity + drawing (Part A) and PCM + general aptitude (Part B). 3 sessions per year — best score counts.",
    durationMin: 180,
    totalQuestions: 125,
    totalMarks: 200,
    marksPerQ: 1.6,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 60_000,
  },
  {
    code: "NID_DAT",
    name: "NID Design Aptitude Test",
    shortName: "NID DAT",
    category: "UNIVERSITY" as const,
    description:
      "National Institute of Design entrance — DAT Prelims (objective design aptitude) followed by DAT Mains (studio test + interview). Gates entry to B.Des at NID Ahmedabad / Gandhinagar / Kurukshetra / Bhopal / Jorhat / Amaravati.",
    durationMin: 180,
    totalQuestions: 50,
    totalMarks: 100,
    marksPerQ: 2,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 25_000,
  },
  {
    code: "NIFT",
    name: "NIFT Entrance Examination",
    shortName: "NIFT",
    category: "UNIVERSITY" as const,
    description:
      "National Institute of Fashion Technology entrance — Creative Ability Test (CAT) + General Ability Test (GAT) followed by Situation Test (B.Des) or Group Discussion + Personal Interview (B.FTech). Admission to 18 NIFT campuses for B.Des / B.FTech / M.Des / M.F.M / M.FTech.",
    durationMin: 180,
    totalQuestions: 150,
    totalMarks: 150,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN"] as const,
    candidatesPerYear: 40_000,
  },
  {
    code: "UCEED",
    name: "Undergraduate Common Entrance Examination for Design (UCEED)",
    shortName: "UCEED",
    category: "UNIVERSITY" as const,
    description:
      "Joint design admission test conducted by IIT Bombay — gates entry to B.Des at IIT Bombay, IIT Guwahati, IIT Hyderabad, IIITDM Jabalpur and IIT Roorkee. Visualisation + observation + analytical reasoning + language + creativity.",
    durationMin: 180,
    totalQuestions: 60,
    totalMarks: 240,
    marksPerQ: 4,
    negativeMark: 0.71,
    languages: ["EN"] as const,
    candidatesPerYear: 14_000,
  },
  {
    code: "AILET",
    name: "All India Law Entrance Test (NLU Delhi)",
    shortName: "AILET",
    category: "LAW" as const,
    description:
      "National Law University Delhi's separate entrance test (NLU Delhi does not use CLAT). Pattern: English + Current Affairs/GK + Logical Reasoning. 5-year integrated LLB UG admission to ~120 seats at NLU Delhi.",
    durationMin: 90,
    totalQuestions: 150,
    totalMarks: 150,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN"] as const,
    candidatesPerYear: 30_000,
  },
  {
    code: "LSAT_INDIA",
    name: "LSAT India",
    shortName: "LSAT India",
    category: "LAW" as const,
    description:
      "Pearson-conducted version of the Law School Admission Test for India — gate to law programmes at Jindal Global Law School (JGLS) and ~80 affiliated colleges. Pattern: Analytical Reasoning + 2 Logical Reasoning + Reading Comprehension. No negative marking.",
    durationMin: 140,
    totalQuestions: 92,
    totalMarks: 92,
    marksPerQ: 1,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 20_000,
  },
  {
    code: "CA_FOUNDATION",
    name: "CA Foundation (ICAI)",
    shortName: "CA Foundation",
    category: "OTHER" as const,
    description:
      "Institute of Chartered Accountants of India entry-level examination for the CA course. 4 papers: Principles & Practice of Accounting, Business Laws + BCR, Business Mathematics + Logical Reasoning + Statistics, Business Economics + BCK. Held twice yearly (May/June + November/December).",
    durationMin: 180,
    totalQuestions: 100,
    totalMarks: 100,
    marksPerQ: 1,
    negativeMark: 0.25,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 350_000,
  },
  {
    code: "CS_FOUNDATION",
    name: "CS Foundation (ICSI / CSEET)",
    shortName: "CS Foundation (CSEET)",
    category: "OTHER" as const,
    description:
      "Institute of Company Secretaries of India's Company Secretary Executive Entrance Test (CSEET, replaced earlier CS Foundation). 4 papers: Business Communication, Legal Aptitude + Logical Reasoning, Economics + Business Environment, Current Affairs + Psychometric. Held 4 times yearly.",
    durationMin: 120,
    totalQuestions: 140,
    totalMarks: 200,
    marksPerQ: 1.4,
    negativeMark: 0,
    languages: ["EN", "HI"] as const,
    candidatesPerYear: 80_000,
  },
  {
    code: "NEET_PG",
    name: "National Eligibility cum Entrance Test (PG)",
    shortName: "NEET PG",
    category: "MEDICAL" as const,
    description:
      "Single national medical PG entrance test conducted by NBEMS — gate to MD / MS / DNB / Diploma admissions across all government and private medical colleges in India.",
    durationMin: 210,
    totalQuestions: 200,
    totalMarks: 800,
    marksPerQ: 4,
    negativeMark: 1,
    languages: ["EN"] as const,
    candidatesPerYear: 200_000,
  },

  // ── BATCH 7 SEED — Statistical / Math institutes ──
  {
    code: "ISI_BSTAT",
    name: "ISI Admission Test (B.Stat / B.Math)",
    shortName: "ISI B.Stat / B.Math",
    category: "UNIVERSITY" as const,
    description:
      "Indian Statistical Institute admission test for the 3-year B.Stat (Hons) at ISI Kolkata and B.Math (Hons) at ISI Bangalore. Single objective + subjective math paper; one of the most rigorous undergraduate math entrances in India.",
    durationMin: 240,
    totalQuestions: 38,
    totalMarks: 188,
    marksPerQ: 4,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 12_000,
  },
  {
    code: "CMI_ADMISSION",
    name: "CMI Admission Test (B.Sc / M.Sc)",
    shortName: "CMI Admission",
    category: "UNIVERSITY" as const,
    description:
      "Chennai Mathematical Institute entrance for B.Sc (Hons) in Mathematics + CS, Physics, and Data Science. JEE Advanced rank holders can apply via JEE route; the CMI Admission Test is the alternative direct entry.",
    durationMin: 180,
    totalQuestions: 35,
    totalMarks: 140,
    marksPerQ: 4,
    negativeMark: 0,
    languages: ["EN"] as const,
    candidatesPerYear: 8_000,
  },
];

export async function seedExams() {
  console.log(`Seeding ${examsSeed.length} exams...`);
  for (const e of examsSeed) {
    await prisma.exam.upsert({
      where: { code: e.code },
      update: {
        name: e.name,
        shortName: e.shortName,
        category: e.category,
        description: e.description,
        durationMin: e.durationMin,
        totalQuestions: e.totalQuestions,
        totalMarks: e.totalMarks,
        marksPerQ: e.marksPerQ,
        negativeMark: e.negativeMark,
        languages: [...e.languages],
        candidatesPerYear: e.candidatesPerYear,
      },
      create: {
        code: e.code,
        name: e.name,
        shortName: e.shortName,
        category: e.category,
        description: e.description,
        durationMin: e.durationMin,
        totalQuestions: e.totalQuestions,
        totalMarks: e.totalMarks,
        marksPerQ: e.marksPerQ,
        negativeMark: e.negativeMark,
        languages: [...e.languages],
        candidatesPerYear: e.candidatesPerYear,
      },
    });
    console.log(`  ✓ ${e.code} — ${e.shortName}`);
  }
  console.log("Done.");
}

if (require.main === module) {
  seedExams()
    .catch((err) => {
      console.error(err);
      process.exit(1);
    })
    .finally(() => prisma.$disconnect());
}
