// State-level exam metadata seeder.
//
// Covers the most-popular recruitment exam for each Indian state + UT.
// Syllabi for these are filled in iteratively (separate seed files per
// exam) using the same SubjectSeed/TopicSeed pattern. Once a syllabus is
// added, plug its seedXxxSyllabus() into seed/exams/seed-all.ts.
//
// Sources cross-checked at write-time: each State PSC's official site
// (e.g. tnpsc.gov.in, kpsc.kar.nic.in, mpsc.gov.in, upsc.gov.in for some
// UTs, etc.). PSC marketing materials and Adda247/BYJU's Exam Prep used
// for cross-validation.

import { PrismaClient } from "@prisma/client";
import { INDIAN_STATES } from "../../src/lib/states";
export { INDIAN_STATES };

const prisma = new PrismaClient();

// State-level exam catalogue. ~45 entries — the most-attempted / most-
// requested exam for each state's PSC + a few of the bigger states' high-
// volume secondary exams (UPSSSC, MPSC TET, etc.).
//
// Code conventions:
//   <STATE_CODE>_<EXAM_SHORTCODE>  e.g. TN_TNPSC_GROUP2, UP_UPPSC_PCS
// Languages: include the state's primary language(s) wherever the PSC
// publishes the paper; English is always offered. Negative-mark and
// duration values reflect the published Prelims / Tier-1 of each.

export const stateExamsSeed = [
  // ── Tamil Nadu ─────────────────────────────────────────────────────────
  { code: "TN_TNPSC_GROUP1", state: "TN", name: "TNPSC Group I (Combined Civil Services - I, Prelims)", shortName: "TNPSC Group I",
    description: "Tamil Nadu Public Service Commission Group I Prelims — single GS paper, 200 MCQs in 3 hours, for Deputy Collector / DSP / Asst Commissioner posts.",
    durationMin: 180, totalQuestions: 200, totalMarks: 300, marksPerQ: 1.5, negativeMark: 1 / 3,
    languages: ["EN", "TA"] as const, candidatesPerYear: 600_000 },
  { code: "TN_TNPSC_GROUP2", state: "TN", name: "TNPSC Group II/IIA (Combined Civil Services - II, Prelims)", shortName: "TNPSC Group II",
    description: "TNPSC Group II/IIA Prelims — single GS paper, 200 MCQs in 3 hours, for Sub-Registrar, Assistant Inspector etc.",
    durationMin: 180, totalQuestions: 200, totalMarks: 300, marksPerQ: 1.5, negativeMark: 1 / 3,
    languages: ["EN", "TA"] as const, candidatesPerYear: 1_500_000 },
  { code: "TN_TNPSC_GROUP4", state: "TN", name: "TNPSC Group IV", shortName: "TNPSC Group IV",
    description: "TNPSC Group IV — VAO + Junior Assistant + Typist combined exam. 200 MCQs in 3 hours covering GS, Aptitude, and General Tamil.",
    durationMin: 180, totalQuestions: 200, totalMarks: 300, marksPerQ: 1.5, negativeMark: 1 / 3,
    languages: ["EN", "TA"] as const, candidatesPerYear: 2_500_000 },
  // ── Karnataka ──────────────────────────────────────────────────────────
  { code: "KA_KPSC_KAS", state: "KA", name: "Karnataka Administrative Service (KAS) Prelims", shortName: "KPSC KAS",
    description: "KPSC KAS Prelims — two papers (GS Paper 1, CSAT-style Paper 2). 200 MCQs each, 2 hours each.",
    durationMin: 240, totalQuestions: 400, totalMarks: 400, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "KN"] as const, candidatesPerYear: 350_000 },
  // ── Maharashtra ────────────────────────────────────────────────────────
  { code: "MH_MPSC_RAJYASEVA", state: "MH", name: "MPSC Rajyaseva (State Service) Prelims", shortName: "MPSC Rajyaseva",
    description: "Maharashtra PSC State Service Prelims — Paper 1 (GS, 100 Qs) + Paper 2 (CSAT, 80 Qs). 200 marks each, 2 hours each.",
    durationMin: 240, totalQuestions: 180, totalMarks: 400, marksPerQ: 2, negativeMark: 0.5,
    languages: ["EN", "MR"] as const, candidatesPerYear: 700_000 },
  { code: "MH_MAHATET", state: "MH", name: "Maharashtra Teacher Eligibility Test (MAHA TET)", shortName: "MAHA TET",
    description: "Maharashtra TET Paper I (Class 1-5) and Paper II (Class 6-8). 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "MR"] as const, candidatesPerYear: 800_000 },
  // ── Uttar Pradesh ──────────────────────────────────────────────────────
  { code: "UP_UPPSC_PCS", state: "UP", name: "UPPSC Combined State Service (PCS) Prelims", shortName: "UPPSC PCS",
    description: "UP PSC PCS Prelims — Paper 1 (GS, 150 Qs, 2 hr) + Paper 2 (CSAT, 100 Qs, 2 hr).",
    durationMin: 240, totalQuestions: 250, totalMarks: 400, marksPerQ: 2, negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const, candidatesPerYear: 600_000 },
  { code: "UP_UPSSSC_PET", state: "UP", name: "UPSSSC Preliminary Eligibility Test (PET)", shortName: "UPSSSC PET",
    description: "UPSSSC PET — common Prelim for all Group C posts in UP. 100 MCQs in 2 hours covering GS, history, geography, science, math, Hindi, English, current affairs.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 4_000_000 },
  { code: "UP_UPTET", state: "UP", name: "Uttar Pradesh Teacher Eligibility Test (UPTET)", shortName: "UPTET",
    description: "UP TET Paper I (Class 1-5) + Paper II (Class 6-8). 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_500_000 },
  // ── Bihar ──────────────────────────────────────────────────────────────
  { code: "BR_BPSC_CCE", state: "BR", name: "BPSC Combined Competitive Exam (CCE) Prelims", shortName: "BPSC CCE",
    description: "Bihar PSC CCE Prelims — single GS paper, 150 MCQs in 2 hours, for Deputy SP / DSP / Block Development Officer posts.",
    durationMin: 120, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 500_000 },
  // ── West Bengal ────────────────────────────────────────────────────────
  { code: "WB_WBCS", state: "WB", name: "West Bengal Civil Service (Exec) Prelims", shortName: "WBCS",
    description: "West Bengal PSC WBCS Prelims — single GS paper, 200 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "BN"] as const, candidatesPerYear: 250_000 },
  // ── Rajasthan ──────────────────────────────────────────────────────────
  { code: "RJ_RPSC_RAS", state: "RJ", name: "Rajasthan Administrative Service (RAS) Prelims", shortName: "RPSC RAS",
    description: "Rajasthan PSC RAS Prelims — single GS paper, 150 MCQs in 3 hours, for State Civil/Police services.",
    durationMin: 180, totalQuestions: 150, totalMarks: 200, marksPerQ: 1.33, negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const, candidatesPerYear: 600_000 },
  // ── Madhya Pradesh ─────────────────────────────────────────────────────
  { code: "MP_MPPSC_SSE", state: "MP", name: "MPPSC State Service Exam (SSE) Prelims", shortName: "MPPSC SSE",
    description: "MP PSC State Service Prelims — Paper 1 (GS, 100 Qs, 200 marks) + Paper 2 (CSAT, 100 Qs, 200 marks). 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 350_000 },
  // ── Andhra Pradesh ─────────────────────────────────────────────────────
  { code: "AP_APPSC_GROUP1", state: "AP", name: "APPSC Group I Services Prelims", shortName: "APPSC Group I",
    description: "Andhra Pradesh PSC Group I Prelims — Paper 1 + Paper 2 (CSAT) screening test for Deputy Collector / DSP posts.",
    durationMin: 240, totalQuestions: 240, totalMarks: 240, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "TE"] as const, candidatesPerYear: 200_000 },
  { code: "AP_APPSC_GROUP2", state: "AP", name: "APPSC Group II Services Prelims", shortName: "APPSC Group II",
    description: "APPSC Group II Prelims — single GS paper, 150 MCQs in 2.5 hours for non-gazetted Group II posts.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "TE"] as const, candidatesPerYear: 700_000 },
  // ── Telangana ──────────────────────────────────────────────────────────
  { code: "TS_TSPSC_GROUP1", state: "TS", name: "TSPSC Group I Services Prelims", shortName: "TSPSC Group I",
    description: "Telangana PSC Group I Prelims — single GS paper, 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "TE"] as const, candidatesPerYear: 300_000 },
  { code: "TS_TSPSC_GROUP2", state: "TS", name: "TSPSC Group II Services", shortName: "TSPSC Group II",
    description: "TSPSC Group II — 4-paper objective exam (GS, History/Polity/Society, Economy & Development, Telangana Movement & State Formation). 150 Qs each.",
    durationMin: 600, totalQuestions: 600, totalMarks: 600, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 800_000 },
  // ── Kerala ─────────────────────────────────────────────────────────────
  { code: "KL_KPSC_LDC", state: "KL", name: "Kerala PSC Lower Division Clerk (LDC)", shortName: "Kerala LDC",
    description: "Kerala Public Service Commission LDC — 100 MCQs in 1.25 hours covering GK, GS, Maths, Mental Ability, Malayalam/English.",
    durationMin: 75, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "ML"] as const, candidatesPerYear: 1_200_000 },
  // ── Gujarat ────────────────────────────────────────────────────────────
  { code: "GJ_GPSC_CLASS12", state: "GJ", name: "GPSC Class 1-2 Prelims", shortName: "GPSC Class 1-2",
    description: "Gujarat PSC State Service Class 1-2 Prelims — 200 MCQs in 3 hours covering GS + GK + Aptitude.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "GU"] as const, candidatesPerYear: 250_000 },
  // ── Haryana ────────────────────────────────────────────────────────────
  { code: "HR_HCS", state: "HR", name: "Haryana Civil Services (HCS) Prelims", shortName: "HCS",
    description: "Haryana PSC HCS Prelims — single objective paper, 100 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 200_000 },
  // ── Himachal Pradesh ───────────────────────────────────────────────────
  { code: "HP_HPAS", state: "HP", name: "HPPSC HP Administrative Service (HPAS) Prelims", shortName: "HPAS",
    description: "Himachal PSC HPAS Prelims — Paper 1 (GS) + Paper 2 (CSAT). 200 MCQs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 80_000 },
  // ── Punjab ─────────────────────────────────────────────────────────────
  { code: "PB_PCS", state: "PB", name: "Punjab Civil Service (PCS) Prelims", shortName: "Punjab PCS",
    description: "Punjab PSC PCS Prelims — Paper 1 (GS) + Paper 2 (CSAT). 100 MCQs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 0.25,
    languages: ["EN", "PA"] as const, candidatesPerYear: 150_000 },
  // ── Odisha ─────────────────────────────────────────────────────────────
  { code: "OD_OPSC_OAS", state: "OD", name: "Odisha PSC Civil Services (OAS) Prelims", shortName: "OPSC OAS",
    description: "Odisha PSC OAS Prelims — Paper 1 (GS) + Paper 2 (CSAT). 100 MCQs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 1 / 3,
    languages: ["EN"] as const, candidatesPerYear: 200_000 },
  // ── Jharkhand ──────────────────────────────────────────────────────────
  { code: "JH_JPSC_CCE", state: "JH", name: "JPSC Combined Civil Service Prelims", shortName: "JPSC CCE",
    description: "Jharkhand PSC CCE Prelims — Paper 1 (GS) + Paper 2 (Jharkhand-specific). 100 Qs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 250_000 },
  // ── Chhattisgarh ───────────────────────────────────────────────────────
  { code: "CG_CGPSC_SSE", state: "CG", name: "CGPSC State Service Exam (SSE) Prelims", shortName: "CGPSC SSE",
    description: "Chhattisgarh PSC SSE Prelims — Paper 1 (GS) + Paper 2 (CSAT). 100 Qs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const, candidatesPerYear: 220_000 },
  // ── Uttarakhand ────────────────────────────────────────────────────────
  { code: "UK_UKPSC_PCS", state: "UK", name: "Uttarakhand PSC Prelims", shortName: "UKPSC PCS",
    description: "Uttarakhand PCS Prelims — single objective paper, 150 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const, candidatesPerYear: 90_000 },
  // ── Assam ──────────────────────────────────────────────────────────────
  { code: "AS_APSC_CCE", state: "AS", name: "APSC Combined Competitive Exam (CCE) Prelims", shortName: "APSC CCE",
    description: "Assam PSC CCE Prelims — single GS paper, 200 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 80_000 },
  // ── Goa ────────────────────────────────────────────────────────────────
  { code: "GA_GPSC", state: "GA", name: "Goa PSC State Service Prelims", shortName: "Goa PSC",
    description: "Goa PSC State Service Prelims — single objective paper covering GS + Goa-specific knowledge.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 15_000 },
  // ── Manipur ────────────────────────────────────────────────────────────
  { code: "MN_MPSC", state: "MN", name: "Manipur PSC Civil Services Prelims", shortName: "Manipur PSC",
    description: "Manipur PSC Civil Services Prelims — Paper 1 (GS) + Paper 2 (CSAT). 100 Qs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 25_000 },
  // ── Meghalaya ──────────────────────────────────────────────────────────
  { code: "ML_MPSC", state: "ML", name: "Meghalaya PSC Civil Services Prelims", shortName: "Meghalaya PSC",
    description: "Meghalaya PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 20_000 },
  // ── Mizoram ────────────────────────────────────────────────────────────
  { code: "MZ_MPSC", state: "MZ", name: "Mizoram PSC Civil Services Prelims", shortName: "Mizoram PSC",
    description: "Mizoram PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 18_000 },
  // ── Nagaland ───────────────────────────────────────────────────────────
  { code: "NL_NPSC", state: "NL", name: "Nagaland PSC Civil Services Prelims", shortName: "Nagaland PSC",
    description: "Nagaland PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 20_000 },
  // ── Tripura ────────────────────────────────────────────────────────────
  { code: "TR_TPSC", state: "TR", name: "Tripura PSC Civil Services Prelims", shortName: "Tripura PSC",
    description: "Tripura PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "BN"] as const, candidatesPerYear: 30_000 },
  // ── Sikkim ─────────────────────────────────────────────────────────────
  { code: "SK_SPSC", state: "SK", name: "Sikkim PSC Civil Services Prelims", shortName: "Sikkim PSC",
    description: "Sikkim PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 12_000 },
  // ── Arunachal Pradesh ──────────────────────────────────────────────────
  { code: "AR_APPSC_AR", state: "AR", name: "Arunachal Pradesh PSC Civil Services Prelims", shortName: "APPSC (AR)",
    description: "Arunachal Pradesh PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 22_000 },
  // ── Union Territories ─────────────────────────────────────────────────
  { code: "DL_DSSSB_TGT", state: "DL", name: "Delhi DSSSB Trained Graduate Teacher (TGT)", shortName: "DSSSB TGT",
    description: "Delhi Subordinate Services Selection Board TGT — Tier 1 + Tier 2. 200 MCQs in 2 hours covering GA, GI, Reasoning, Math, Hindi/English, Subject knowledge.",
    durationMin: 120, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 600_000 },
  { code: "JK_JKPSC_KAS", state: "JK", name: "J&K PSC Combined Competitive Exam (KAS) Prelims", shortName: "JKPSC KAS",
    description: "J&K PSC KAS Prelims — Paper 1 (GS) + Paper 2 (CSAT). 200 MCQs each, 2 hours each.",
    durationMin: 240, totalQuestions: 200, totalMarks: 400, marksPerQ: 2, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 100_000 },
  { code: "CH_CHANDIGARH_PCS", state: "CH", name: "Chandigarh UT Civil Services Prelims", shortName: "Chandigarh PCS",
    description: "Chandigarh UT Public Service Commission Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 15_000 },
  { code: "PY_PPSC", state: "PY", name: "Puducherry PSC Civil Services Prelims", shortName: "Puducherry PSC",
    description: "Puducherry PSC Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "TA"] as const, candidatesPerYear: 18_000 },
  { code: "LA_LPSC", state: "LA", name: "Ladakh UT Civil Services Prelims", shortName: "Ladakh PSC",
    description: "Ladakh UT Public Service Commission Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 8_000 },
  { code: "AN_ANIIPS", state: "AN", name: "Andaman & Nicobar Islands Police Constable", shortName: "AN Police",
    description: "Andaman & Nicobar Police Constable recruitment exam — General Awareness, Reasoning, Math, English/Hindi.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 20_000 },
  { code: "DN_DDPSC", state: "DN", name: "Dadra & Nagar Haveli + Daman & Diu UT Recruitment", shortName: "DD&DNH Recruitment",
    description: "DD & DNH UT recruitment screening — General Awareness, Reasoning, Math, English.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 12_000 },
  { code: "LD_LAKSHADWEEP", state: "LD", name: "Lakshadweep UT Civil Services Prelims", shortName: "Lakshadweep PSC",
    description: "Lakshadweep UT Civil Services Prelims — single GS paper.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 5_000 },

  // ─────────────────────────────────────────────────────────────────────
  // STATE ENGINEERING / MEDICAL ENTRANCE
  // ─────────────────────────────────────────────────────────────────────
  { code: "MH_MHTCET", state: "MH", name: "Maharashtra Common Entrance Test (MHT-CET)", shortName: "MHT-CET",
    description: "MHT-CET — Maharashtra state engineering + pharmacy entrance. PCM/PCB tracks, 150 MCQs in 3 hours covering Class 11+12 NCERT.",
    durationMin: 180, totalQuestions: 150, totalMarks: 200, marksPerQ: 1.33, negativeMark: 0,
    languages: ["EN", "MR"] as const, candidatesPerYear: 600_000 },
  { code: "KA_KCET", state: "KA", name: "Karnataka Common Entrance Test (KCET)", shortName: "KCET",
    description: "KCET — Karnataka state engineering + pharmacy + agriculture entrance. 4 papers (Phy/Chem/Math/Bio), 60 Qs each.",
    durationMin: 320, totalQuestions: 240, totalMarks: 240, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "KN"] as const, candidatesPerYear: 250_000 },
  { code: "KA_COMEDK", state: "KA", name: "COMEDK UGET Karnataka", shortName: "COMEDK UGET",
    description: "COMEDK UGET — Karnataka private engineering colleges entrance. Phy + Chem + Math, 180 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 180, totalMarks: 180, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 80_000 },
  { code: "KL_KEAM", state: "KL", name: "Kerala Engineering Architecture Medical (KEAM)", shortName: "KEAM",
    description: "KEAM — Kerala state engineering entrance. 2 papers: Phy+Chem (120 Qs), Math (120 Qs). 2.5 hours each.",
    durationMin: 300, totalQuestions: 240, totalMarks: 960, marksPerQ: 4, negativeMark: 1,
    languages: ["EN"] as const, candidatesPerYear: 100_000 },
  { code: "AP_EAMCET", state: "AP", name: "AP Engineering Agricultural Medical Common Entrance Test (AP EAMCET)", shortName: "AP EAMCET",
    description: "AP EAMCET — Andhra Pradesh state engineering / pharmacy entrance. 160 MCQs in 3 hours covering Phy/Chem/Math.",
    durationMin: 180, totalQuestions: 160, totalMarks: 160, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 250_000 },
  { code: "TS_EAMCET", state: "TS", name: "TS Engineering Agricultural Medical Common Entrance Test (TS EAMCET)", shortName: "TS EAMCET",
    description: "TS EAMCET — Telangana state engineering entrance. 160 MCQs in 3 hours covering Phy/Chem/Math (or Bio for AGRI).",
    durationMin: 180, totalQuestions: 160, totalMarks: 160, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 200_000 },
  { code: "WB_WBJEE", state: "WB", name: "West Bengal Joint Entrance Examination (WBJEE)", shortName: "WBJEE",
    description: "WBJEE — West Bengal state engineering / pharmacy / architecture entrance. Paper 1 (Math), Paper 2 (Phy+Chem). 4 hours total.",
    durationMin: 240, totalQuestions: 155, totalMarks: 200, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "BN"] as const, candidatesPerYear: 130_000 },
  { code: "JK_JKCET", state: "JK", name: "J&K Common Entrance Test (JKCET)", shortName: "JKCET",
    description: "JKCET — J&K state engineering entrance. 180 MCQs in 3 hours covering Phy/Chem/Math.",
    durationMin: 180, totalQuestions: 180, totalMarks: 180, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 25_000 },
  { code: "UP_UPCET", state: "UP", name: "UP Combined Entrance Test (UPCET / CUET PG-style)", shortName: "UPCET",
    description: "UPCET — Uttar Pradesh state engineering / management entrance (now via CUET). 100 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 100, totalMarks: 400, marksPerQ: 4, negativeMark: 1,
    languages: ["EN", "HI"] as const, candidatesPerYear: 70_000 },
  { code: "GJ_GUJCET", state: "GJ", name: "Gujarat Common Entrance Test (GUJCET)", shortName: "GUJCET",
    description: "GUJCET — Gujarat state engineering / pharmacy entrance. Phy/Chem/Math, 120 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 120, totalMarks: 120, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "GU"] as const, candidatesPerYear: 130_000 },
  { code: "PB_PUNJABCET", state: "PB", name: "Punjab Engineering College Common Entrance Test (PCET)", shortName: "Punjab CET",
    description: "Punjab Common Entrance Test — Phy/Chem/Math, 100 Qs in 2 hours for state engineering colleges.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "PA"] as const, candidatesPerYear: 50_000 },
  { code: "OD_OJEE", state: "OD", name: "Odisha Joint Entrance Examination (OJEE)", shortName: "OJEE",
    description: "OJEE — Odisha state engineering / pharmacy / MBA entrance. Multiple track papers, 120 MCQs in 2 hours each.",
    durationMin: 120, totalQuestions: 120, totalMarks: 120, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 60_000 },
  { code: "RJ_REAP", state: "RJ", name: "Rajasthan Engineering Admission Process (REAP)", shortName: "REAP",
    description: "REAP — Rajasthan state engineering admission. JEE Main score-based, no separate exam, but tracked here for syllabus alignment.",
    durationMin: 180, totalQuestions: 90, totalMarks: 300, marksPerQ: 4, negativeMark: 1,
    languages: ["EN", "HI"] as const, candidatesPerYear: 80_000 },
  { code: "BR_BCECE", state: "BR", name: "Bihar Combined Entrance Competitive Examination (BCECE)", shortName: "BCECE",
    description: "BCECE — Bihar state engineering / pharmacy entrance. Phy/Chem/Math (or Bio), 100 Qs in 1.5 hours each section.",
    durationMin: 270, totalQuestions: 300, totalMarks: 400, marksPerQ: 1.33, negativeMark: 0.33,
    languages: ["EN", "HI"] as const, candidatesPerYear: 100_000 },
  { code: "AS_ASSAMCEE", state: "AS", name: "Assam Combined Entrance Examination (Assam CEE)", shortName: "Assam CEE",
    description: "Assam CEE — Assam state engineering entrance. Phy/Chem/Math, 120 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 120, totalMarks: 480, marksPerQ: 4, negativeMark: 1,
    languages: ["EN"] as const, candidatesPerYear: 30_000 },

  // ─────────────────────────────────────────────────────────────────────
  // STATE TEACHER ELIGIBILITY TESTS (TET)
  // ─────────────────────────────────────────────────────────────────────
  { code: "TN_TET", state: "TN", name: "Tamil Nadu Teacher Eligibility Test (TN TET)", shortName: "TN TET",
    description: "TN TET — Tamil Nadu Teacher Eligibility Test for primary + upper-primary teaching posts. Paper I + Paper II.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TA"] as const, candidatesPerYear: 700_000 },
  { code: "KA_KARTET", state: "KA", name: "Karnataka Teacher Eligibility Test (KAR TET)", shortName: "KAR TET",
    description: "KAR TET — Karnataka TET. Paper I (Class 1-5) + Paper II (Class 6-8). 150 MCQs each.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "KN"] as const, candidatesPerYear: 500_000 },
  { code: "AP_TET", state: "AP", name: "Andhra Pradesh Teacher Eligibility Test (AP TET)", shortName: "AP TET",
    description: "AP TET — Andhra Pradesh TET for primary / secondary teacher recruitment. Paper I + Paper II.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 600_000 },
  { code: "TS_TET", state: "TS", name: "Telangana Teacher Eligibility Test (TS TET)", shortName: "TS TET",
    description: "TS TET — Telangana TET. Paper I + Paper II. 150 MCQs in 2.5 hours each.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 500_000 },
  { code: "KL_KTET", state: "KL", name: "Kerala Teacher Eligibility Test (KTET)", shortName: "KTET",
    description: "KTET — Kerala TET. Categories I-IV for different teaching levels. 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "ML"] as const, candidatesPerYear: 300_000 },
  { code: "MP_TET", state: "MP", name: "Madhya Pradesh Teacher Eligibility Test (MP TET)", shortName: "MP TET",
    description: "MP TET — Varg-1, Varg-2, Varg-3 (different teaching levels). 150 Qs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 600_000 },
  { code: "GJ_TET", state: "GJ", name: "Gujarat Teacher Eligibility Test (GTET / GSET)", shortName: "GTET",
    description: "GTET — Gujarat State Eligibility Test for state lecturer / teacher posts. Multi-paper.",
    durationMin: 180, totalQuestions: 150, totalMarks: 300, marksPerQ: 2, negativeMark: 0,
    languages: ["EN", "GU"] as const, candidatesPerYear: 250_000 },
  { code: "BR_TET", state: "BR", name: "Bihar Teacher Eligibility Test (Bihar TET)", shortName: "Bihar TET",
    description: "Bihar TET — for primary + upper-primary teacher recruitment. Paper I + Paper II.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 800_000 },
  { code: "RJ_REET", state: "RJ", name: "Rajasthan Eligibility Examination for Teachers (REET)", shortName: "REET",
    description: "REET — Rajasthan TET. Level 1 (Class 1-5) + Level 2 (Class 6-8). 150 MCQs in 2.5 hours each.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_500_000 },
  { code: "HP_TET", state: "HP", name: "Himachal Pradesh Teacher Eligibility Test (HP TET)", shortName: "HP TET",
    description: "HP TET — Categories: TGT, JBT, Shastri, Punjabi, Urdu. 150 Qs each, 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 80_000 },
  { code: "JK_KASHMIR_TET", state: "JK", name: "J&K Teacher Eligibility Test (JKTET)", shortName: "JKTET",
    description: "JKTET — J&K Teacher Eligibility Test. Paper I + Paper II. 150 Qs each.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 100_000 },
  { code: "OD_TET", state: "OD", name: "Odisha Teacher Eligibility Test (OTET)", shortName: "OTET",
    description: "OTET — Odisha TET for primary + upper-primary teaching. Paper I + Paper II.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 250_000 },
  { code: "WB_TET", state: "WB", name: "West Bengal Teacher Eligibility Test (WB TET)", shortName: "WB TET",
    description: "WB TET — West Bengal Primary + Upper-Primary TET. 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "BN"] as const, candidatesPerYear: 1_000_000 },
  { code: "PB_TET", state: "PB", name: "Punjab State Teacher Eligibility Test (PSTET)", shortName: "PSTET",
    description: "PSTET — Punjab State TET. 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "PA"] as const, candidatesPerYear: 200_000 },
  { code: "HR_TET", state: "HR", name: "Haryana Teacher Eligibility Test (HTET)", shortName: "HTET",
    description: "HTET — Haryana TET. Levels 1-3 for PRT, TGT, PGT. 150 MCQs each.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 250_000 },
  { code: "UK_TET", state: "UK", name: "Uttarakhand Teacher Eligibility Test (UTET)", shortName: "UTET",
    description: "UTET — Uttarakhand TET. Paper I + Paper II.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 150_000 },
  { code: "AS_TET", state: "AS", name: "Assam Teacher Eligibility Test (Assam TET)", shortName: "Assam TET",
    description: "Assam TET — Lower-Primary + Upper-Primary TET. 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 150_000 },
  { code: "JH_TET", state: "JH", name: "Jharkhand Teacher Eligibility Test (JTET)", shortName: "JTET",
    description: "JTET — Jharkhand TET. Paper I + Paper II.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 200_000 },
  { code: "CG_TET", state: "CG", name: "Chhattisgarh Teacher Eligibility Test (CG TET)", shortName: "CG TET",
    description: "CG TET — Chhattisgarh TET. Paper I + Paper II. 150 MCQs each.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 200_000 },

  // ─────────────────────────────────────────────────────────────────────
  // STATE POLICE / CONSTABLE / SI
  // ─────────────────────────────────────────────────────────────────────
  { code: "UP_POLICE_CONSTABLE", state: "UP", name: "UP Police Constable", shortName: "UP Police Constable",
    description: "UPPRPB — UP Police Constable Recruitment. 150 MCQs in 2 hours covering GK, Reasoning, Math, Hindi.",
    durationMin: 120, totalQuestions: 150, totalMarks: 300, marksPerQ: 2, negativeMark: 0.5,
    languages: ["EN", "HI"] as const, candidatesPerYear: 4_500_000 },
  { code: "UP_POLICE_SI", state: "UP", name: "UP Police Sub-Inspector (SI)", shortName: "UP Police SI",
    description: "UPPRPB — UP Police SI exam. 160 MCQs in 2 hours. Hindi + GK + Reasoning + Math.",
    durationMin: 120, totalQuestions: 160, totalMarks: 400, marksPerQ: 2.5, negativeMark: 0.5,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_500_000 },
  { code: "MH_POLICE_BHARTI", state: "MH", name: "Maharashtra Police Bharti (Constable)", shortName: "MH Police Bharti",
    description: "Maharashtra Police Constable recruitment. 100 MCQs in 90 mins covering GK, Math, Reasoning, Marathi.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "MR"] as const, candidatesPerYear: 1_500_000 },
  { code: "TN_POLICE_PC", state: "TN", name: "Tamil Nadu Police Constable (TNUSRB Grade II)", shortName: "TN Police PC",
    description: "TNUSRB Grade II PC exam. 100 MCQs in 90 mins covering GK, Math, Tamil/English.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TA"] as const, candidatesPerYear: 1_200_000 },
  { code: "KA_POLICE_PC", state: "KA", name: "Karnataka State Police Constable (KSP)", shortName: "KSP Constable",
    description: "Karnataka Police PC exam. 100 MCQs in 90 mins covering GK, Math, Reasoning, Kannada.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "KN"] as const, candidatesPerYear: 700_000 },
  { code: "BR_POLICE_PC", state: "BR", name: "Bihar Police Constable (CSBC)", shortName: "Bihar Police",
    description: "CSBC — Bihar Police Constable Recruitment. 100 MCQs in 2 hours covering GK, Math, Hindi.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_800_000 },
  { code: "BR_POLICE_SI", state: "BR", name: "Bihar Police Sub-Inspector (BPSSC SI)", shortName: "BPSSC SI",
    description: "BPSSC — Bihar Police SI Prelims. 100 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 100, totalMarks: 200, marksPerQ: 2, negativeMark: 0.5,
    languages: ["EN", "HI"] as const, candidatesPerYear: 800_000 },
  { code: "RJ_POLICE_PC", state: "RJ", name: "Rajasthan Police Constable", shortName: "RJ Police PC",
    description: "Rajasthan Police Constable Recruitment. 150 MCQs in 2 hours covering Reasoning, GK, Hindi.",
    durationMin: 120, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_700_000 },
  { code: "MP_POLICE_PC", state: "MP", name: "MP Police Constable (MPPEB)", shortName: "MP Police PC",
    description: "MPPEB — MP Police Constable. 100 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_200_000 },
  { code: "DL_POLICE_PC", state: "DL", name: "Delhi Police Constable (SSC)", shortName: "Delhi Police PC",
    description: "SSC Delhi Police Constable Recruitment. 100 MCQs in 90 mins.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_500_000 },
  { code: "WB_POLICE_PC", state: "WB", name: "West Bengal Police Constable (WBP)", shortName: "WB Police PC",
    description: "WBP — West Bengal Police Constable. 100 MCQs in 1 hour.",
    durationMin: 60, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "BN"] as const, candidatesPerYear: 800_000 },
  { code: "GJ_POLICE_PC", state: "GJ", name: "Gujarat Police Constable (Lokrakshak)", shortName: "GJ Police PC",
    description: "Gujarat Lokrakshak Recruitment Board Constable. 100 MCQs in 1 hour.",
    durationMin: 60, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "GU"] as const, candidatesPerYear: 700_000 },
  { code: "HR_POLICE_PC", state: "HR", name: "Haryana Police Constable (HSSC)", shortName: "HR Police PC",
    description: "HSSC — Haryana Police Constable. 100 MCQs in 90 mins.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 600_000 },
  { code: "PB_POLICE_PC", state: "PB", name: "Punjab Police Constable", shortName: "PB Police PC",
    description: "Punjab Police Constable. 100 MCQs in 90 mins.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "PA"] as const, candidatesPerYear: 350_000 },
  { code: "TS_POLICE_PC", state: "TS", name: "Telangana Police Constable (TSLPRB)", shortName: "TS Police PC",
    description: "TSLPRB — Telangana State Level Police Recruitment. 200 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 600_000 },
  { code: "AP_POLICE_PC", state: "AP", name: "AP Police Constable (APSLPRB)", shortName: "AP Police PC",
    description: "APSLPRB — AP State Level Police Recruitment Board Constable. 200 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 500_000 },
  { code: "OD_POLICE_PC", state: "OD", name: "Odisha Police Constable (OSSC)", shortName: "OD Police PC",
    description: "OSSC — Odisha Police Constable. 100 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 350_000 },

  // ─────────────────────────────────────────────────────────────────────
  // STATE STAFF SELECTION COMMISSIONS / GROUP-D RECRUITMENT
  // ─────────────────────────────────────────────────────────────────────
  { code: "UP_UPPSC_RO_ARO", state: "UP", name: "UPPSC Review Officer / Asst Review Officer (RO/ARO)", shortName: "UPPSC RO/ARO",
    description: "UPPSC RO/ARO Prelims — single GS+Hindi paper, 200 MCQs in 3 hours. UP Secretariat clerical posts.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_000_000 },
  { code: "HR_HSSC_CET", state: "HR", name: "Haryana Staff Selection Common Eligibility Test (HSSC CET)", shortName: "HSSC CET",
    description: "HSSC CET — common Prelim for all Group C/D posts in Haryana. 100 MCQs in 1.75 hours.",
    durationMin: 105, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_500_000 },
  { code: "BR_BSSC_INTER", state: "BR", name: "Bihar Staff Selection Commission Intermediate Level (BSSC)", shortName: "BSSC Inter Level",
    description: "BSSC Inter Level — Bihar SSC for clerical posts. Prelims: 150 MCQs in 2 hours covering GK, Math, Reasoning, Hindi.",
    durationMin: 120, totalQuestions: 150, totalMarks: 600, marksPerQ: 4, negativeMark: 1,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_300_000 },
  { code: "RJ_RSMSSB", state: "RJ", name: "Rajasthan Subordinate & Ministerial Services Selection Board (RSMSSB)", shortName: "RSMSSB",
    description: "RSMSSB — Rajasthan Group C / Junior Engineer / Patwari recruitment. 150 MCQs in 2 hours typically.",
    durationMin: 120, totalQuestions: 150, totalMarks: 300, marksPerQ: 2, negativeMark: 1 / 3,
    languages: ["EN", "HI"] as const, candidatesPerYear: 2_000_000 },
  { code: "PB_PSSSB", state: "PB", name: "Punjab Subordinate Services Selection Board (PSSSB)", shortName: "PSSSB",
    description: "PSSSB — Punjab Group C clerical / PCS Junior posts. 100-150 MCQs depending on post.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "PA"] as const, candidatesPerYear: 400_000 },
  { code: "JK_JKSSB", state: "JK", name: "J&K Services Selection Board (JKSSB)", shortName: "JKSSB",
    description: "JKSSB — J&K Group C / Junior Assistant / Naib Tehsildar exams. 120 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 120, totalMarks: 120, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN"] as const, candidatesPerYear: 250_000 },
  { code: "UK_UKSSSC", state: "UK", name: "Uttarakhand Subordinate Services Selection Commission (UKSSSC)", shortName: "UKSSSC",
    description: "UKSSSC — Uttarakhand Group C posts (VDO, Patwari, Junior Asst). 100 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 350_000 },
  { code: "HP_HPSSSB", state: "HP", name: "HP Subordinate Services Selection Board (HPSSSB)", shortName: "HPSSSB",
    description: "HPSSSB Hamirpur — HP Group C posts. 200 MCQs in 2 hours typical.",
    durationMin: 120, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 400_000 },
  { code: "WB_PSC_CLERK", state: "WB", name: "West Bengal PSC Clerkship", shortName: "WBPSC Clerkship",
    description: "WBPSC Clerkship — West Bengal PSC Lower Division Clerk. 100 MCQs in 1.5 hours.",
    durationMin: 90, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "BN"] as const, candidatesPerYear: 500_000 },
  { code: "MP_MPESB", state: "MP", name: "Madhya Pradesh Employees Selection Board (MPESB) Group 1/2/3", shortName: "MPESB Group",
    description: "MPESB (formerly MPPEB) — MP Group recruitment. 200 MCQs in 3 hours covering subject-specific + GK.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 1_000_000 },
  { code: "GJ_GSSSB", state: "GJ", name: "Gujarat Subordinate Service Selection Board (GSSSB)", shortName: "GSSSB",
    description: "GSSSB — Gujarat Group C posts. 100 MCQs in 1 hour.",
    durationMin: 60, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "GU"] as const, candidatesPerYear: 700_000 },
  { code: "AP_APPSC_GROUP3", state: "AP", name: "APPSC Group III Services", shortName: "APPSC Group III",
    description: "APPSC Group III — Panchayat Secretary / Junior Assistant. 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "TE"] as const, candidatesPerYear: 400_000 },
  { code: "TS_TSPSC_GROUP3", state: "TS", name: "TSPSC Group III Services", shortName: "TSPSC Group III",
    description: "TSPSC Group III — multi-paper objective exam for non-gazetted Group III posts.",
    durationMin: 180, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "TE"] as const, candidatesPerYear: 500_000 },
  { code: "TS_TSPSC_GROUP4", state: "TS", name: "TSPSC Group IV Services", shortName: "TSPSC Group IV",
    description: "TSPSC Group IV — Junior Assistant / Junior Accountant / Bill Collector. 150 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 1 / 3,
    languages: ["EN", "TE"] as const, candidatesPerYear: 600_000 },
  { code: "TN_TNUSRB_SI", state: "TN", name: "TNUSRB Sub-Inspector (TN Police SI)", shortName: "TN Police SI",
    description: "TNUSRB — TN Police SI Recruitment. 200 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TA"] as const, candidatesPerYear: 400_000 },
  { code: "KA_KPSC_GROUP_C", state: "KA", name: "KPSC Group C Recruitment", shortName: "KPSC Group C",
    description: "KPSC Group C — Karnataka clerical / asst posts. 200 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0.25,
    languages: ["EN", "KN"] as const, candidatesPerYear: 500_000 },
  { code: "MH_MPSC_GROUP_C", state: "MH", name: "MPSC Group C Combined Services", shortName: "MPSC Group C",
    description: "MPSC Group C — Maharashtra clerical posts (Tax Assistant / Sub-Registrar / Industries Inspector).",
    durationMin: 60, totalQuestions: 100, totalMarks: 100, marksPerQ: 1, negativeMark: 0.5,
    languages: ["EN", "MR"] as const, candidatesPerYear: 600_000 },

  // ─────────────────────────────────────────────────────────────────────
  // STATE POLYTECHNIC / NURSING / PARAMEDICAL ENTRANCE
  // ─────────────────────────────────────────────────────────────────────
  { code: "UP_JEECUP", state: "UP", name: "UP Joint Entrance Exam Polytechnic (JEECUP)", shortName: "UP JEECUP",
    description: "JEECUP — UP Polytechnic state entrance. 100 MCQs in 2.5 hours covering Math + Phy + Chem.",
    durationMin: 150, totalQuestions: 100, totalMarks: 400, marksPerQ: 4, negativeMark: 1,
    languages: ["EN", "HI"] as const, candidatesPerYear: 250_000 },
  { code: "AP_POLYCET", state: "AP", name: "AP Polytechnic Common Entrance Test (AP POLYCET)", shortName: "AP POLYCET",
    description: "AP POLYCET — Andhra Pradesh Polytechnic entrance. 120 MCQs in 2 hours covering Math + Phy + Chem.",
    durationMin: 120, totalQuestions: 120, totalMarks: 120, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 100_000 },
  { code: "TS_POLYCET", state: "TS", name: "TS Polytechnic Common Entrance Test (TS POLYCET)", shortName: "TS POLYCET",
    description: "TS POLYCET — Telangana Polytechnic entrance. 150 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 80_000 },
  { code: "UK_POLYTECHNIC", state: "UK", name: "Uttarakhand Polytechnic JEEP", shortName: "UK JEEP",
    description: "JEEP — Uttarakhand Polytechnic entrance. 100 MCQs in 3 hours.",
    durationMin: 180, totalQuestions: 100, totalMarks: 400, marksPerQ: 4, negativeMark: 1,
    languages: ["EN", "HI"] as const, candidatesPerYear: 50_000 },
  { code: "HP_POLYTECHNIC", state: "HP", name: "HP Polytechnic Admission Test (HP PAT)", shortName: "HP PAT",
    description: "HP PAT — HP Polytechnic Admission Test. 150 MCQs in 2 hours.",
    durationMin: 120, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "HI"] as const, candidatesPerYear: 25_000 },
  { code: "BR_DCECE", state: "BR", name: "Bihar Diploma Combined Entrance Competitive Examination (DCECE)", shortName: "Bihar DCECE",
    description: "DCECE — Bihar Polytechnic + Paramedical + Para Dental entrance. 90 MCQs in 2.25 hours.",
    durationMin: 135, totalQuestions: 90, totalMarks: 450, marksPerQ: 5, negativeMark: 1.25,
    languages: ["EN", "HI"] as const, candidatesPerYear: 130_000 },
  { code: "MH_NURSING_CET", state: "MH", name: "Maharashtra B.Sc. Nursing CET", shortName: "MH Nursing CET",
    description: "MH B.Sc. Nursing Common Entrance Test. 200 MCQs in 3 hours covering Phy/Chem/Bio.",
    durationMin: 180, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "MR"] as const, candidatesPerYear: 50_000 },

  // ─────────────────────────────────────────────────────────────────────
  // STATE LAW / MGMT / PG ENTRANCE
  // ─────────────────────────────────────────────────────────────────────
  { code: "MH_MAHCET_LAW", state: "MH", name: "MH-CET Law (3-yr & 5-yr LL.B.)", shortName: "MH-CET Law",
    description: "MH-CET Law — Maharashtra state law entrance. 150 MCQs in 2 hours covering Legal Aptitude + Logical Reasoning + GK + English + Math.",
    durationMin: 120, totalQuestions: 150, totalMarks: 150, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 60_000 },
  { code: "AP_LAWCET", state: "AP", name: "AP LAWCET", shortName: "AP LAWCET",
    description: "AP LAWCET — Andhra Pradesh Law Common Entrance Test. 120 MCQs in 1.5 hours.",
    durationMin: 90, totalQuestions: 120, totalMarks: 120, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 40_000 },
  { code: "TS_LAWCET", state: "TS", name: "TS LAWCET", shortName: "TS LAWCET",
    description: "TS LAWCET — Telangana Law Common Entrance Test. 120 MCQs in 1.5 hours.",
    durationMin: 90, totalQuestions: 120, totalMarks: 120, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 35_000 },
  { code: "MH_MAHCET_MBA", state: "MH", name: "MH-CET MBA / MMS", shortName: "MH-CET MBA",
    description: "MH-CET MBA — Maharashtra MBA entrance. 200 MCQs in 2.5 hours covering Logical Reasoning + Quant + Verbal Ability.",
    durationMin: 150, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN"] as const, candidatesPerYear: 130_000 },
  { code: "AP_ICET", state: "AP", name: "AP Integrated Common Entrance Test (AP ICET)", shortName: "AP ICET",
    description: "AP ICET — MBA / MCA state entrance. 200 MCQs in 2.5 hours covering Analytical + Math + Communication Ability.",
    durationMin: 150, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 60_000 },
  { code: "TS_ICET", state: "TS", name: "TS Integrated Common Entrance Test (TS ICET)", shortName: "TS ICET",
    description: "TS ICET — MBA / MCA Telangana state entrance. 200 MCQs in 2.5 hours.",
    durationMin: 150, totalQuestions: 200, totalMarks: 200, marksPerQ: 1, negativeMark: 0,
    languages: ["EN", "TE"] as const, candidatesPerYear: 50_000 },
];

export async function seedStateExams() {
  console.log(`Seeding ${stateExamsSeed.length} state-level exams...`);
  for (const e of stateExamsSeed) {
    const data = {
      name: e.name,
      shortName: e.shortName,
      category: "STATE_LEVEL" as const,
      description: e.description,
      durationMin: e.durationMin,
      totalQuestions: e.totalQuestions,
      totalMarks: e.totalMarks,
      marksPerQ: e.marksPerQ,
      negativeMark: e.negativeMark,
      languages: [...e.languages],
      candidatesPerYear: e.candidatesPerYear,
      state: e.state,
    };
    await prisma.exam.upsert({
      where: { code: e.code },
      update: data,
      create: { code: e.code, ...data },
    });
    console.log(`  ✓ ${e.code.padEnd(20)} ${e.shortName} [${e.state}]`);
  }
  console.log(`Done. Seeded ${stateExamsSeed.length} state exams across ${INDIAN_STATES.length} states/UTs.`);
}

if (require.main === module) {
  seedStateExams()
    .catch((err) => { console.error(err); process.exit(1); })
    .finally(() => prisma.$disconnect());
}
