// Passage bank for the typing test. Exam-neutral, factual prose in the
// register real skill tests use (SSC DEST passages are plain office/GK
// prose). ~90-110 words each so a 2-minute test never runs out when
// combined (the player concatenates passages if the typist is fast).

export const EN_PASSAGES: string[] = [
  "The Indian Constitution came into force on the twenty sixth of January nineteen fifty. It provides for a parliamentary form of government with a clear division of powers between the Union and the States. The President is the constitutional head of the executive, while real power rests with the Council of Ministers headed by the Prime Minister. The Supreme Court stands at the apex of the judicial system and acts as the guardian of the Constitution. Every citizen enjoys fundamental rights, and these rights are enforceable in a court of law.",
  "Banks play a central role in the economic development of a country. They accept deposits from the public and lend money to farmers, traders and industries. The Reserve Bank of India regulates the banking system and controls the supply of money in the economy. In recent years, digital payments have grown rapidly across the country. Mobile banking has reached remote villages, and small merchants now accept payments through simple QR codes. Financial literacy remains important so that every household can use these services safely and avoid fraud.",
  "The railway network in India is among the largest in the world. Every day thousands of trains carry passengers and goods across the length and breadth of the country. The railways provide employment to lakhs of people and connect distant regions with major cities. Modern signalling systems and electrification have improved both the speed and the safety of train services. New dedicated freight corridors are reducing the burden on passenger lines, and station redevelopment projects are changing the way travellers experience the railways.",
  "Monsoon rains are the lifeline of Indian agriculture. A good monsoon raises the production of food grains and supports the income of millions of farming families. The south west monsoon usually reaches the Kerala coast in the first week of June and then advances northwards. Farmers plan the sowing of kharif crops such as paddy, cotton and pulses around its arrival. When the rains fail, reservoirs run low, drinking water becomes scarce and the demand for rural employment rises sharply. Weather forecasting has therefore become vital for planning.",
  "Public examinations in India are conducted with great care to ensure fairness. Question papers are prepared by subject experts and kept under strict security until the day of the test. Candidates must reach the examination centre well before the reporting time with a valid admit card and an identity proof. Electronic devices are not allowed inside the hall. After the examination, answer keys are published so that candidates can raise objections within the given window. Final results are declared only after all objections are examined.",
  "Regular practice is the foundation of success in any competitive examination. Toppers rarely depend on long hours alone; they depend on consistent daily study, honest revision of mistakes and timely mock tests. A written timetable helps an aspirant balance new topics with revision of old ones. Short breaks between study sessions keep the mind fresh. Above all, an aspirant must protect their health, because steady preparation over months requires good sleep, simple food and a calm, determined state of mind.",
];

export const HI_PASSAGES: string[] = [
  "भारत का संविधान छब्बीस जनवरी उन्नीस सौ पचास को लागू हुआ। संविधान ने देश में संसदीय शासन प्रणाली की स्थापना की। राष्ट्रपति कार्यपालिका का संवैधानिक प्रमुख होता है, जबकि वास्तविक शक्ति प्रधानमंत्री के नेतृत्व वाले मंत्रिपरिषद के पास होती है। सर्वोच्च न्यायालय संविधान का संरक्षक है। प्रत्येक नागरिक को मौलिक अधिकार प्राप्त हैं और इन अधिकारों की रक्षा के लिए वह न्यायालय जा सकता है।",
  "बैंक देश के आर्थिक विकास में महत्वपूर्ण भूमिका निभाते हैं। वे जनता से जमा स्वीकार करते हैं और किसानों, व्यापारियों तथा उद्योगों को ऋण देते हैं। भारतीय रिज़र्व बैंक बैंकिंग प्रणाली का नियमन करता है। पिछले कुछ वर्षों में डिजिटल भुगतान का प्रसार तेजी से हुआ है। मोबाइल बैंकिंग दूर दराज के गांवों तक पहुंच गई है और छोटे दुकानदार भी क्यूआर कोड से भुगतान स्वीकार करते हैं। वित्तीय साक्षरता से हर परिवार इन सेवाओं का सुरक्षित उपयोग कर सकता है।",
  "भारतीय रेल विश्व के सबसे बड़े रेल नेटवर्क में से एक है। प्रतिदिन हजारों रेलगाड़ियां यात्रियों और माल को देश के कोने कोने तक पहुंचाती हैं। रेलवे लाखों लोगों को रोजगार देती है और दूर दराज के क्षेत्रों को बड़े शहरों से जोड़ती है। आधुनिक सिग्नल प्रणाली और विद्युतीकरण से रेल सेवाओं की गति और सुरक्षा दोनों में सुधार हुआ है। नए माल गलियारों से यात्री लाइनों पर दबाव कम हो रहा है।",
  "मानसून की वर्षा भारतीय कृषि की जीवन रेखा है। अच्छे मानसून से खाद्यान्न का उत्पादन बढ़ता है और करोड़ों किसान परिवारों की आय सुरक्षित रहती है। दक्षिण पश्चिम मानसून सामान्यतः जून के पहले सप्ताह में केरल तट पर पहुंचता है। किसान धान, कपास और दलहन जैसी खरीफ फसलों की बुवाई इसी के अनुसार करते हैं। वर्षा न होने पर जलाशय सूखने लगते हैं और पेयजल की समस्या बढ़ जाती है। इसलिए मौसम पूर्वानुमान का महत्व बहुत बढ़ गया है।",
  "सार्वजनिक परीक्षाएं पूरी सावधानी से आयोजित की जाती हैं ताकि सभी अभ्यर्थियों को समान अवसर मिले। प्रश्न पत्र विषय विशेषज्ञों द्वारा तैयार किए जाते हैं और परीक्षा के दिन तक कड़ी सुरक्षा में रखे जाते हैं। अभ्यर्थियों को वैध प्रवेश पत्र और पहचान पत्र के साथ समय से पहले परीक्षा केंद्र पहुंचना चाहिए। परीक्षा हॉल में इलेक्ट्रॉनिक उपकरण ले जाना वर्जित है। परीक्षा के बाद उत्तर कुंजी जारी की जाती है जिस पर निर्धारित अवधि में आपत्ति दर्ज की जा सकती है।",
  "नियमित अभ्यास किसी भी प्रतियोगी परीक्षा में सफलता की नींव है। सफल अभ्यर्थी केवल लंबे घंटों पर निर्भर नहीं रहते, बल्कि प्रतिदिन के नियमित अध्ययन, गलतियों के ईमानदार पुनरावलोकन और समय पर मॉक टेस्ट पर भरोसा करते हैं। लिखित समय सारणी से नए विषयों और पुराने विषयों की पुनरावृत्ति में संतुलन बनता है। अध्ययन के बीच छोटे विराम मन को ताजा रखते हैं। अच्छी नींद, सादा भोजन और शांत मन महीनों की तैयारी के लिए आवश्यक हैं।",
];
