// robots.txt — generated by Next App Router from this file.
//
// Default-allow + explicit-disallow is Google's preferred pattern
// (vs an explicit allow-list, which has to be exhaustively
// maintained every time a new section ships).
//
// Privacy gates:
//   - /api/ — JSON endpoints, nothing useful to a crawler
//   - /admin/ — operator UI, must never index
//   - /dashboard, /me/ — personal data
//   - /chat — auth-gated AI tutor, conversations are private
//   - /mocks/, /attempts/ — per-user state
//   - /logout, /login (callback flows have state) — auth flows
//   - /onboarding — wizard, no public value to crawlers
//
// NOT disallowed, on purpose: /share/ (per-attempt score landings). They
// carry robots noindex,nofollow in their own metadata (13 Sep 2026); a
// crawler has to fetch the page to see that, and a disallowed URL can
// still be indexed bare from inbound WhatsApp / X links.
//
// Allow surfaces beneath /me that are public: /u/[handle] is in the
// /u/ tree (NOT /me/), so it stays indexable for opted-in users.
//
// /schooling (26 Sep 2026, school go-live): the school section is public
// for every crawler above — Googlebot, Bingbot and each AI fetcher — and is
// named in each rule's allow list so the intent is visible in robots.txt
// itself (the default "/" already covers it). Which school page a crawler
// may INDEX is the page's own robots meta (a chapter without Shishya
// content is noindex, follow); robots.txt only says it may be fetched.
//
// Sitemap + host annotations are read by Google + Bing. crawl-delay
// for archive.org / commoncrawl avoids hammering during nightly
// scrapes.

import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? "https://shishya.in";
  // Private / auth-gated / operator paths kept out of EVERY crawler —
  // including AI crawlers (no personal data in answer engines / training).
  const privatePaths = [
    "/api/",
    "/admin/",
    "/admin",
    "/dashboard",
    "/dashboard/",
    "/today",
    "/today/",
    "/me",
    "/me/",
    "/chat",
    "/chat/",
    "/mocks/",
    "/attempts/",
    "/login",
    "/logout",
    "/onboarding",
    // Mentor desk (auth-gated, per-student data). NOTE: "/mentor/" +
    // "/mentor$" — a bare "/mentor" prefix rule would also block the
    // PUBLIC /mentors marketing page.
    "/mentor/",
    "/mentor$",
    // Avoid indexing query-string variants of pages we surface
    // canonically (filtered exam browse, scholarship browser).
    "/exams/browse?*",
    "/scholarships?*",
  ];
  // AI / answer-engine crawlers — explicitly WELCOMED (chatgpt.com is our
  // #1 referral; we want to be the source LLMs cite for Indian exams).
  // Each gets full public access minus the private paths.
  const aiCrawlers = [
    "GPTBot", // OpenAI training
    "OAI-SearchBot", // ChatGPT search
    "ChatGPT-User", // ChatGPT live browsing
    "PerplexityBot",
    "Perplexity-User",
    "ClaudeBot",
    "anthropic-ai",
    "Claude-User",
    "Claude-SearchBot", // Claude search index — the crawler behind Claude's web search
    "Google-Extended", // Gemini
    "GoogleOther", // Google AI/R&D crawls (feeds Gemini)
    "Applebot",
    "Applebot-Extended",
    "Bytespider",
    "Amazonbot",
    "cohere-ai",
    "meta-externalagent", // Meta AI
    "DuckAssistBot", // DuckDuckGo AI answers
    "MistralAI-User",
    "YouBot",
  ];
  const BURSTY_TRAINING_CRAWLERS = new Set(["ClaudeBot", "anthropic-ai", "Bytespider"]);
  // Public sections named explicitly beside "/" (see the /schooling note above).
  const allowPaths = ["/", "/schooling", "/schooling/"];
  return {
    rules: [
      {
        // Default policy for all user agents — open by default, tight
        // on private/auth-gated/operator paths.
        userAgent: "*",
        allow: allowPaths,
        disallow: privatePaths,
      },
      // Training crawlers that arrive in bursts get a crawl delay (13 Sep
      // 2026: ClaudeBot fetched 32,636 pages on 11 Sep, ~5,000 per half hour
      // between 07:00 and 12:30 IST, the same hours human page views ran
      // 60-75% below the day before). 2 s still allows ~43k pages a day, more
      // than any day seen, so only the burst is shaped. Search and
      // live-answer fetchers (OAI-SearchBot, ChatGPT-User, Claude-SearchBot,
      // Claude-User, Perplexity) are never delayed.
      ...aiCrawlers.map((userAgent) => ({
        userAgent,
        allow: allowPaths,
        disallow: privatePaths,
        ...(BURSTY_TRAINING_CRAWLERS.has(userAgent) ? { crawlDelay: 2 } : {}),
      })),
      {
        // Common Crawl (feeds many LLM training sets — good for AI
        // visibility): allow public content, keep private paths out, be
        // polite on crawl rate (Neon load during full-site crawls).
        userAgent: "CCBot",
        allow: allowPaths,
        disallow: privatePaths,
        crawlDelay: 5,
      },
      {
        userAgent: "ia_archiver",
        crawlDelay: 10,
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
