// robots.txt — generated by Next App Router from this file.
//
// Default-allow + explicit-disallow is Google's preferred pattern
// (vs an explicit allow-list, which has to be exhaustively
// maintained every time a new section ships).
//
// Privacy gates:
//   - /api/ — JSON endpoints, nothing useful to a crawler
//   - /admin/ — operator UI, must never index
//   - /dashboard, /me/ — personal data
//   - /chat — auth-gated AI tutor, conversations are private
//   - /mocks/, /attempts/ — per-user state
//   - /logout, /login (callback flows have state) — auth flows
//   - /onboarding — wizard, no public value to crawlers
//
// Allow surfaces beneath /me that are public: /u/[handle] is in the
// /u/ tree (NOT /me/), so it stays indexable for opted-in users.
//
// Sitemap + host annotations are read by Google + Bing. crawl-delay
// for archive.org / commoncrawl avoids hammering during nightly
// scrapes.

import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? "https://shishya.in";
  return {
    rules: [
      {
        // Default policy for all user agents — open by default, tight
        // on private/auth-gated/operator paths.
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/admin/",
          "/admin",
          "/dashboard",
          "/dashboard/",
          "/me",
          "/me/",
          "/chat",
          "/chat/",
          "/mocks/",
          "/attempts/",
          "/login",
          "/logout",
          "/onboarding",
          // Avoid indexing query-string variants of pages we already
          // surface canonically (filtered exam browse, scholarship
          // browser). The canonical URLs are in the sitemap.
          "/exams/browse?*",
          "/scholarships?*",
        ],
      },
      {
        // Common Crawl / archival bots: be polite. Reduces load on
        // Neon's free tier during periodic full-site crawls.
        userAgent: "CCBot",
        crawlDelay: 5,
      },
      {
        userAgent: "ia_archiver",
        crawlDelay: 10,
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
