// School content — persistence plan (26 Sep 2026).
//
// Pure: the exact rows scripts/school-content-batch.ts writes once a reply
// has passed content-parse.ts, so the tests pin them without a database.
//
//   Notes → TopicTeachingNote (1:1 by topicId; what /exams/[code]/topics/
//   [topicCode] renders through hasUsableNotes). generatedBy is the tag
//   "school-batch:<model>". The model has no metadata column, so the
//   provenance blob (class, book, chapter, official URL, prompt version, run)
//   travels as an HTML comment at the end of the markdown: invisible when
//   rendered, greppable in the DB, and the journal holds the same record.
//   A re-generation (--force) resets validatedAt / validatorId exactly as
//   scripts/generate-topic-notes.ts does — the content changed.
//
//   Questions → Question rows: validated:false, source AI_GENERATED (the
//   enum's "generated by Claude, awaiting validation"), tags [<chapter
//   code>, "school", "gen:<date>"] plus the model's own kebab tags, and
//   metadata.provenance in the factory's spirit (pipeline, generatedBy,
//   groundedSources, producedAt) with a `school` block and an honest
//   `label`. The verify runner later adds metadata.factoryVerify beside it
//   and flips validated on ACCEPT — that is the only door to "served", and
//   even then the SCHOOL_BOARD exam stays inactive (founder rule 5).

import type { Prisma } from "@prisma/client";
import { PROVENANCE_COMMENT_PREFIX, type NotesProvenance } from "./provenance";
import type { CandidateQuestion } from "../ai/factory/types";
import { MCQ_PROMPT_VERSION, MCQ_SET_SIZE, MCQ_SETS_PER_CHAPTER, MCQ_SET_MIX, NOTES_PROMPT_VERSION, type DifficultyMix, type SchoolChapter, chapterIdentity } from "./content-prompts";

export const SCHOOL_PIPELINE = "school-batch-v1";
export const SCHOOL_TAG = "school";
/** The tag every question of one generation day carries, e.g. gen:2026-09-26. */
export function genTag(now: Date): string {
  return `gen:${now.toISOString().slice(0, 10)}`;
}
export function notesGeneratedBy(model: string): string {
  return `school-batch:${model}`;
}

// ── Notes ───────────────────────────────────────────────────────────────

// 26 Sep 2026: the provenance comment helpers moved to ./provenance so the
// school pages can strip the comment without importing this file (it pulls
// content-prompts.ts and the Anthropic client). Same names, re-exported.
export { PROVENANCE_COMMENT_PREFIX, readProvenanceComment, stripProvenanceComment } from "./provenance";
export type { NotesProvenance } from "./provenance";

export function notesProvenance(ch: SchoolChapter, opts: { model: string; runId: string; now: Date }): NotesProvenance {
  return {
    pipeline: SCHOOL_PIPELINE,
    promptVersion: NOTES_PROMPT_VERSION,
    model: opts.model,
    runId: opts.runId,
    producedAt: opts.now.toISOString(),
    class: ch.cls,
    examCode: ch.examCode,
    subject: ch.subject,
    book: ch.bookCode,
    bookTitle: ch.bookTitle,
    chapter: ch.chapterNumber,
    chapterTitle: ch.title,
    topicCode: ch.topicCode,
    officialUrl: ch.officialUrl,
    groundedIn: [`ncert-chapter-identity:${ch.examCode}:${ch.topicCode}`],
  };
}

export function provenanceComment(p: NotesProvenance): string {
  // "--" may not appear inside an HTML comment; the JSON has none, but keep it safe.
  return `${PROVENANCE_COMMENT_PREFIX}${JSON.stringify(p).replace(/--/g, "- -")} -->`;
}

export interface NoteWritePlan {
  topicId: string;
  where: { topicId: string };
  create: { topicId: string; content: string; generatedAt: Date; generatedBy: string };
  update: { content: string; generatedAt: Date; generatedBy: string; validatedAt: null; validatorId: null };
  provenance: NotesProvenance;
}

/** The upsert for one chapter's notes (content = validated markdown from parseSchoolNotes + the provenance comment). */
export function planNoteWrite(ch: SchoolChapter, content: string, opts: { model: string; runId: string; now: Date }): NoteWritePlan {
  const provenance = notesProvenance(ch, opts);
  const stored = `${content.trimEnd()}\n\n${provenanceComment(provenance)}\n`;
  const generatedBy = notesGeneratedBy(opts.model);
  return {
    topicId: ch.topicId,
    where: { topicId: ch.topicId },
    create: { topicId: ch.topicId, content: stored, generatedAt: opts.now, generatedBy },
    update: { content: stored, generatedAt: opts.now, generatedBy, validatedAt: null, validatorId: null },
    provenance,
  };
}

// ── Questions ───────────────────────────────────────────────────────────

/** The honest, student-readable label stored with every school question. */
export function questionLabel(ch: SchoolChapter): string {
  return `Practice question written by AI for ${chapterIdentity(ch)} — Shishya's own, not an NCERT exercise or a board question.`;
}

export interface SchoolQuestionProvenance {
  pipeline: typeof SCHOOL_PIPELINE;
  generatedBy: string;
  promptVersion: string;
  groundedSources: string[];
  producedAt: string;
  label: string;
  school: {
    class: number;
    examCode: string;
    subject: string;
    book: string;
    bookTitle: string;
    chapter: string | null;
    chapterTitle: string;
    topicCode: string;
    officialUrl: string;
    setIndex: number;
    runId: string;
  };
}

const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
/** Model tags kept per question after the three fixed ones. */
export const MODEL_TAGS_MAX = 3;

export function questionTags(ch: SchoolChapter, candidate: Pick<CandidateQuestion, "tags">, now: Date): string[] {
  const fixed = [ch.topicCode, SCHOOL_TAG, genTag(now)];
  const own = [...new Set(candidate.tags.map((t) => t.trim().toLowerCase()).filter((t) => KEBAB.test(t) && t.length <= 40 && !fixed.includes(t)))].slice(0, MODEL_TAGS_MAX);
  return [...fixed, ...own];
}

export type QuestionRowPlan = Omit<Prisma.QuestionUncheckedCreateInput, "metadata"> & { metadata: { provenance: SchoolQuestionProvenance } };

/** The create rows for one set's clean, deduplicated candidates. */
export function planQuestionRows(
  ch: SchoolChapter,
  examId: string,
  candidates: CandidateQuestion[],
  opts: { model: string; runId: string; setIndex: number; now: Date },
): QuestionRowPlan[] {
  const producedAt = opts.now.toISOString();
  const label = questionLabel(ch);
  return candidates.map((c) => ({
    examId,
    topicId: ch.topicId,
    type: "MCQ",
    difficulty: c.difficulty,
    body: c.body,
    options: c.options,
    answerKey: c.answerKey,
    solution: c.solution,
    language: "EN",
    source: "AI_GENERATED",
    validated: false,
    validatedBy: null,
    validatedAt: null,
    tags: questionTags(ch, c, opts.now),
    pyqYear: null,
    metadata: {
      provenance: {
        pipeline: SCHOOL_PIPELINE,
        generatedBy: opts.model,
        promptVersion: MCQ_PROMPT_VERSION,
        groundedSources: [`ncert-chapter-identity:${ch.examCode}:${ch.topicCode}`, `topic.teachingNote:${ch.topicCode}`],
        producedAt,
        label,
        school: {
          class: ch.cls,
          examCode: ch.examCode,
          subject: ch.subject,
          book: ch.bookCode,
          bookTitle: ch.bookTitle,
          chapter: ch.chapterNumber,
          chapterTitle: ch.title,
          topicCode: ch.topicCode,
          officialUrl: ch.officialUrl,
          setIndex: opts.setIndex,
          runId: opts.runId,
        },
      },
    },
  }));
}

// ── Selection ───────────────────────────────────────────────────────────

/** Sets (0-based indexes) a chapter still needs to reach the target. `existing` = questions already on the chapter (withdrawn ones excluded). --force asks for the full four regardless. */
export function setsNeeded(existing: number, opts: { target?: number; force?: boolean } = {}): number[] {
  const target = opts.target ?? MCQ_SET_SIZE * MCQ_SETS_PER_CHAPTER;
  if (opts.force) return Array.from({ length: MCQ_SETS_PER_CHAPTER }, (_, i) => i);
  const missing = Math.max(0, target - existing);
  const n = Math.min(MCQ_SETS_PER_CHAPTER, Math.ceil(missing / MCQ_SET_SIZE));
  return Array.from({ length: n }, (_, i) => i);
}

/** The mix every set asks for (each set is 4/4/2, so the sum over four sets is the chapter's 16/16/8). */
export function mixForSet(_setIndex: number): DifficultyMix {
  return { ...MCQ_SET_MIX };
}

// ── Resume ──────────────────────────────────────────────────────────────

/** The slice of a journal the resume pruning reads (src/lib/ai/batch.ts BatchJournal, structurally). */
export interface ResumeView {
  requests: Record<string, { customId: string; phase: string; questionId: string; runIndex?: number; status: string }>;
  outputs: {
    notes: Record<string, unknown>;
    notesWritten: Record<string, unknown>;
    gen: Record<string, Record<string, unknown>>;
    written: Record<string, Record<string, unknown>>;
  };
  /** No batch was ever submitted and no submit is pending: nothing was paid for. */
  neverSubmitted: boolean;
}

/**
 * custom_ids of "built" requests a resumed run must NOT submit:
 *   • the run already produced their output (a notes reply parsed or written;
 *     a set parsed or its rows written) — a resume re-enters the phase driver,
 *     which would otherwise submit them again;
 *   • the journal was never submitted (a dry-run journal) and the chapter no
 *     longer needs them — e.g. the 124-chapter dry-run journal resumed after
 *     the 5-chapter pilot wrote those chapters' notes and questions.
 * A request in a journal that HAS submitted batches is kept whatever the DB
 * now holds: mid-run, this run's own earlier writes are what changed the counts.
 */
export function pruneBuiltRequests(
  j: ResumeView,
  need: { notes: Set<string>; sets: Map<string, number[]> },
  phases: { notes: string; gen: string },
): string[] {
  const drop: string[] = [];
  for (const r of Object.values(j.requests)) {
    if (r.status !== "built") continue;
    const set = String(r.runIndex ?? 0);
    const done =
      r.phase === phases.notes
        ? Boolean(j.outputs.notes[r.questionId] || j.outputs.notesWritten[r.questionId])
        : r.phase === phases.gen
          ? Boolean(j.outputs.gen[r.questionId]?.[set] || j.outputs.written[r.questionId]?.[set])
          : false;
    const stale =
      j.neverSubmitted &&
      (r.phase === phases.notes ? !need.notes.has(r.questionId) : r.phase === phases.gen ? !(need.sets.get(r.questionId) ?? []).includes(r.runIndex ?? 0) : false);
    if (done || stale) drop.push(r.customId);
  }
  return drop;
}
