// scripts/build-mocks.ts
//
// Assembles system mocks (Mock.userId = null) for each active exam from
// whatever questions are currently in the DB. Runs after build-content has
// generated enough questions; fully idempotent (existing system mocks are
// updated rather than duplicated).
//
// Per exam, this creates:
//   1) Full Length Practice — random pull, count = exam.totalQuestions
//   2) Topic Drill — top 3 subjects, 15 Qs each
//
// USAGE
//   tsx scripts/build-mocks.ts --all
//   tsx scripts/build-mocks.ts --category OLYMPIAD
//   tsx scripts/build-mocks.ts --exams SSC_CGL,IBPS_PO --min-questions 20
//
// FLAGS
//   --category <name>      restrict to one ExamCategory
//   --exams <CSV>          explicit exam codes
//   --all                  every active exam (default)
//   --min-questions <n>    skip exam if fewer than N total questions exist
//                          (avoids creating laughably-thin mocks; default 20)
//   --include-unvalidated  use AI_GENERATED unvalidated questions too
//                          (default: only validated questions enter mocks)
//   --dry-run              print plan; no DB writes

import { PrismaClient, MockType } from "@prisma/client";

interface CliArgs {
  category?: string;
  exams?: string[];
  all: boolean;
  minQuestions: number;
  includeUnvalidated: boolean;
  dryRun: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const a: any = { all: false, minQuestions: 20, includeUnvalidated: false, dryRun: false };
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => argv[++i];
    switch (arg) {
      case "--category":            a.category = next(); break;
      case "--exams":               a.exams = next().split(",").map((s: string) => s.trim()); break;
      case "--all":                 a.all = true; break;
      case "--min-questions":       a.minQuestions = parseInt(next(), 10); break;
      case "--include-unvalidated": a.includeUnvalidated = true; break;
      case "--dry-run":             a.dryRun = true; break;
    }
  }
  if (!a.category && !a.exams) a.all = true;
  return a as CliArgs;
}

interface MockPlan {
  slug: string;       // stable id used in `generatedBy`
  title: string;
  type: MockType;
  durationMin: number;
  questionIds: string[];
  config: any;
}

async function main() {
  const args = parseArgs(process.argv);
  const prisma = new PrismaClient();

  const where: any = { active: true };
  if (args.category) where.category = args.category;
  if (args.exams) where.code = { in: args.exams };

  const exams = await prisma.exam.findMany({
    where,
    orderBy: { code: "asc" },
    include: {
      subjects: {
        include: {
          topics: { include: { children: true } },
        },
      },
    },
  });

  console.log(`\n=== build-mocks ===`);
  console.log(`Filter:   ${args.category ?? args.exams?.join(",") ?? "all"}`);
  console.log(`Min Qs:   ${args.minQuestions}`);
  console.log(`Source:   ${args.includeUnvalidated ? "validated + AI_GENERATED" : "validated only"}`);
  console.log(`Mode:     ${args.dryRun ? "DRY RUN" : "LIVE"}`);
  console.log(`Exams:    ${exams.length}\n`);

  let createdCount = 0;
  let updatedCount = 0;
  let skippedExams = 0;

  for (const exam of exams) {
    const baseWhere: any = { examId: exam.id };
    if (!args.includeUnvalidated) baseWhere.validated = true;
    const totalAvailable = await prisma.question.count({ where: baseWhere });

    if (totalAvailable < args.minQuestions) {
      console.log(`  (skip) ${exam.code.padEnd(15)} only ${totalAvailable} questions (< ${args.minQuestions})`);
      skippedExams += 1;
      continue;
    }

    const plans: MockPlan[] = [];

    // ── Plan 1: Full Length Practice ────────────────────────────────
    const fullCount = Math.min(exam.totalQuestions, totalAvailable);
    const fullQs = await prisma.question.findMany({
      where: baseWhere,
      take: fullCount,
      orderBy: { id: "asc" },
      select: { id: true },
    });
    plans.push({
      slug: `full-length-practice`,
      title: `${exam.shortName} — Full Length Practice`,
      type: "FULL",
      durationMin: exam.durationMin,
      questionIds: fullQs.map((q) => q.id),
      config: {
        durationMin: exam.durationMin,
        description: `${fullCount} questions mirroring the real exam structure. ${args.includeUnvalidated ? "Includes AI-drafted questions awaiting SME review." : "Only SME-validated questions."}`,
        autoGenerated: true,
      },
    });

    // ── Plan 2: Topic Drills (one per top subject by topic count) ───
    const subjectsBySize = [...exam.subjects].sort((a, b) =>
      (b.topics?.length ?? 0) - (a.topics?.length ?? 0)
    );
    const topSubjects = subjectsBySize.slice(0, 3);
    for (const subj of topSubjects) {
      const topicIds = subj.topics.flatMap((t) => [t.id, ...t.children.map((c) => c.id)]);
      if (topicIds.length === 0) continue;
      const drillQs = await prisma.question.findMany({
        where: { ...baseWhere, topicId: { in: topicIds } },
        take: 15,
        orderBy: { id: "asc" },
        select: { id: true },
      });
      if (drillQs.length < 5) continue; // not worth a mock with <5 Qs

      plans.push({
        slug: `topic-drill-${subj.code.toLowerCase()}`,
        title: `${exam.shortName} — ${subj.name} Drill`,
        type: "SUBJECT",
        durationMin: 20,
        questionIds: drillQs.map((q) => q.id),
        config: {
          durationMin: 20,
          subjectCode: subj.code,
          description: `${drillQs.length}-question warm-up focused on ${subj.name}.`,
          autoGenerated: true,
        },
      });
    }

    console.log(`  → ${exam.code.padEnd(15)} ${plans.length} mock(s) planned (pool: ${totalAvailable} Qs)`);

    if (args.dryRun) continue;

    for (const plan of plans) {
      const generatedBy = `system:auto:${plan.slug}`;
      const existing = await prisma.mock.findFirst({
        where: { examId: exam.id, userId: null, generatedBy },
      });
      if (existing) {
        await prisma.mock.update({
          where: { id: existing.id },
          data: {
            title: plan.title,
            type: plan.type,
            config: plan.config,
            questionIds: plan.questionIds,
          },
        });
        updatedCount += 1;
      } else {
        await prisma.mock.create({
          data: {
            examId: exam.id,
            userId: null,
            title: plan.title,
            type: plan.type,
            config: plan.config,
            questionIds: plan.questionIds,
            generatedBy,
          },
        });
        createdCount += 1;
      }
    }
  }

  await prisma.$disconnect();

  console.log(`\n=== build-mocks summary ===`);
  console.log(`Exams skipped (insufficient Qs): ${skippedExams}`);
  console.log(`System mocks created: ${createdCount}`);
  console.log(`System mocks updated: ${updatedCount}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
