// scripts/fill-mock-gaps.ts
//
// After the popularity sweep finishes, this final pass guarantees every
// active exam has at least one system mock — even tiny / state-level ones
// the sweep skipped or budget-truncated. It does NOT call Anthropic.
//
// Strategy per exam without a system mock:
//   1. If the exam has >= 5 questions (validated OR AI_GENERATED), build
//      one "Quick Practice" mock from up to 30 of them.
//   2. If it has fewer than 5 questions, log it and move on — these exams
//      need seed-content / generate-questions before a mock can exist.
//
// Idempotent. Re-running creates nothing new for an exam that already has
// a system mock.
//
// USAGE
//   npx dotenv-cli -e .env.local -- npx tsx scripts/fill-mock-gaps.ts
//   npx dotenv-cli -e .env.local -- npx tsx scripts/fill-mock-gaps.ts --dry-run

import { PrismaClient } from "@prisma/client";

const args = new Set(process.argv.slice(2));
const dryRun = args.has("--dry-run");

const p = new PrismaClient();

async function main() {
  console.log(`=== fill-mock-gaps ${dryRun ? "(dry-run)" : "(LIVE)"} ===\n`);

  const exams = await p.exam.findMany({
    where: { active: true },
    orderBy: { code: "asc" },
    select: {
      id: true,
      code: true,
      shortName: true,
      totalQuestions: true,
      durationMin: true,
    },
  });

  // Which exams already have at least one system mock?
  const haveMocks = new Set(
    (await p.mock.groupBy({
      by: ["examId"],
      where: { userId: null, examId: { in: exams.map((e) => e.id) } },
      _count: { _all: true },
    })).map((r) => r.examId),
  );

  let built = 0;
  let stillEmpty = 0;
  let skipped = 0;

  for (const e of exams) {
    if (haveMocks.has(e.id)) {
      skipped += 1;
      continue;
    }

    const qs = await p.question.findMany({
      where: { examId: e.id },
      select: { id: true },
      take: 30,
      orderBy: { id: "asc" },
    });

    if (qs.length < 5) {
      console.log(`  (gap)   ${e.code.padEnd(24)} only ${qs.length} questions — needs content seeding`);
      stillEmpty += 1;
      continue;
    }

    const count = Math.min(qs.length, e.totalQuestions || qs.length);
    const ids = qs.slice(0, count).map((q) => q.id);

    console.log(`  → ${e.code.padEnd(24)} build ${count}-Q Quick Practice from any available questions`);
    if (dryRun) {
      built += 1;
      continue;
    }

    await p.mock.create({
      data: {
        examId: e.id,
        userId: null,
        title: `${e.shortName} — Quick Practice`,
        type: "FULL",
        questionIds: ids,
        config: {
          durationMin: e.durationMin || 30,
          description: `${count} questions assembled from the exam's current question pool (may include AI-drafted items pending review).`,
          autoGenerated: true,
          fallback: true,
        },
        generatedBy: "system:auto:fill-gap-quick-practice",
      },
    });
    built += 1;
  }

  console.log(`\n=== summary ===`);
  console.log(`Exams skipped (already had mocks): ${skipped}`);
  console.log(`Exams patched with new Quick Practice mock: ${built}`);
  console.log(`Exams still empty (need content seed): ${stillEmpty}`);

  await p.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
