// /me/report/print — the aspirant's dated status report, print-optimised.
// "Download" = the browser's native save-as-PDF (capsule pattern): works
// on every device, costs nothing, and the artifact survives offline.
// Content = the same Student-360 + this-week-vs-last-week comparison,
// stamped with the date — a different document every day by construction.

import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { buildStudent360 } from "@/lib/student-360";
import { buildWeekCompare } from "@/lib/student-week-compare";
import { Student360View } from "@/components/Student360View";
import { WeekCompareView } from "@/components/WeekCompareView";
import { PrintButton } from "@/components/PrintButton";

export const metadata: Metadata = {
  title: "My status report — Shishya",
  robots: { index: false, follow: false },
};
export const dynamic = "force-dynamic";

export default async function ReportPrintPage() {
  const session = await auth();
  const userId = session?.user?.id;
  if (!userId) redirect("/login?callbackUrl=/me/report");
  const [p, wk] = await Promise.all([buildStudent360(userId), buildWeekCompare(userId)]);
  if (!p) redirect("/dashboard");

  const dateIst = new Date(Date.now() + 5.5 * 3600_000).toISOString().slice(0, 10);

  return (
    <main className="mx-auto max-w-3xl bg-white px-6 py-8 print:px-0 print:py-0">
      <style>{`@media print { header, nav, footer { display: none !important; } body { background: white !important; } }`}</style>
      <div className="mb-4 flex items-center justify-between print:hidden">
        <a href="/me/report" className="text-sm text-ink-500 hover:text-ink-700">← Back to report</a>
        <PrintButton label="Download this report as PDF" />
      </div>

      <div className="border-b-2 border-saffron-500 pb-3">
        <p className="text-lg font-bold text-ink-900">Shishya — Preparation Status Report</p>
        <p className="text-sm text-ink-600">
          {p.name} · {p.exam ? p.exam.short : "no exam picked"}
          {p.daysToExam != null && ` · ${p.daysToExam} days to exam`} · {dateIst}
        </p>
      </div>

      <div className="mt-5">
        <Student360View p={p} viewer="self" />
      </div>

      <div className="mt-6">
        <WeekCompareView wk={wk} />
      </div>

      <p className="mt-8 border-t border-ink-100 pt-3 text-xs text-ink-400">
        Generated by Shishya (shishya.in) on {dateIst} — free, for {p.name}. Tomorrow's report will be different: it moves with your preparation.
      </p>
    </main>
  );
}
