// GENERATED by scripts/build-official-readings.ts — do not edit by hand.
//
// Exam patterns and syllabus places read from the conducting bodies' own
// documents, each read twice (the second reading re-opened every document).
// Only what both readings found is here. Hand-read entries live in
// src/lib/pattern-verified.ts and src/lib/official-syllabus-lines.ts and win
// over an entry of the same key here.

import type { VerifiedPattern } from "@/lib/pattern-verified";
import type { SyllabusDocument } from "@/lib/official-syllabus-lines";

export const READ_PATTERNS: Readonly<Record<string, VerifiedPattern>> = {
  "AP_TET": {
    "code": "AP_TET",
    "stage": "Paper-2A",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Child Development and Pedagogy",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language-I (optional: Telugu, Urdu, Hindi, Kannada, Tamil, Odiya or Sanskrit)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language-II (compulsory: English)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics and Science, or Social Studies, or Language",
        "questions": 60,
        "marks": 60
      }
    ],
    "languages": "",
    "source": {
      "url": "https://tet2dsc.apcfss.in/TET-PDF/APTET%20Information%20Bulliten.pdf",
      "publisher": "Department of School Education, Government of Andhra Pradesh (Commissioner / Director of School Education)",
      "publisherShort": "CSE AP",
      "title": "Information Bulletin for APTET - JUNE - 2026 (read with Notification No.01-APTET-JUNE-2026, Dt: 05-06-2026)",
      "publishedOn": "2026-06-05",
      "para": "Information Bulletin APTET-June-2026: para 6(a) on page 8"
    },
    "checkedOn": "2026-09-29"
  },
  "AS_TET": {
    "code": "AS_TET",
    "stage": "Special TET-2026, Paper I (Lower Primary)",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Child Development & Pedagogy",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language I - Bodo, Garo, Manipuri and Hmar (any one)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language II - English",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Environmental Studies",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "Assamese, Bengali, Bodo, English",
    "source": {
      "url": "https://ssa.assam.gov.in/sites/default/files/swf_utility_folder/departments/ssam_medhassu_in_oid_5/latest/final_advt_special_tet_2026.pdf",
      "publisher": "State Level Empowered Committee, TET, Government of Assam (Department of School Education), notices published by Samagra",
      "publisherShort": "SSA Assam",
      "title": "Advertisement on Special Assam Teacher Eligibility Test (TET)-2026 for Lower Primary & Upper Primary Level (for Bodo,…",
      "publishedOn": "2026-01-06",
      "para": "Para 3 (Structure and Content of Special Assam TET-2026, Paper I table), pages 2-3",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29"
  },
  "CTET": {
    "code": "CTET",
    "stage": "Paper I",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Child Development and Pedagogy",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Environmental Studies",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language I",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language II",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "bilingual (Hindi/English); Language I and II in the two languages the candidate chooses",
    "source": {
      "url": "https://cdnbbsr.s3waas.gov.in/s3443dec3062d0286986e21dc0631734c9/uploads/2026/05/202605111250310617.pdf",
      "publisher": "Central Board of Secondary Education (CBSE), Central Teacher Eligibility Test Unit",
      "publisherShort": "CBSE",
      "title": "Information Bulletin, CTET-September, 2026 (22nd Edition)",
      "publishedOn": "",
      "para": "Para 7, Structure and Content of CTET, printed Page 3 (PDF page 9)"
    },
    "checkedOn": "2026-09-29"
  },
  "DL_DSSSB_TGT": {
    "code": "DL_DSSSB_TGT",
    "stage": "One-tier examination (Technical / Teaching)",
    "questions": 200,
    "marks": 200,
    "durationMin": 120,
    "negativePerWrong": 0.25,
    "sections": [
      {
        "name": "Section A: General Awareness",
        "questions": null,
        "marks": 20
      },
      {
        "name": "Section A: General Intelligence & Reasoning Ability",
        "questions": null,
        "marks": 20
      },
      {
        "name": "Section A: Arithmetical & Numerical Ability",
        "questions": null,
        "marks": 20
      },
      {
        "name": "Section A: Test of Hindi Language & Comprehension",
        "questions": null,
        "marks": 20
      },
      {
        "name": "Section A: Test of English Language & Comprehension",
        "questions": null,
        "marks": 20
      },
      {
        "name": "Section B: Subject concerned, including questions on teaching methodology/B.Ed",
        "questions": 100,
        "marks": 100
      }
    ],
    "languages": "Bilingual (Hindi & English), except the language papers, which are in the language concerned only",
    "source": {
      "url": "https://dsssb.delhi.gov.in/sites/default/files/DSSSB/circulars-orders/final_advt-03-2026.pdf",
      "publisher": "Delhi Subordinate Services Selection Board",
      "publisherShort": "DSSSB",
      "title": "Vacancy Notice, Advertisement No. 03/2026 (Post Codes 21/26 to 45/26, including Trained Graduate Teacher (Computer…",
      "publishedOn": "2026-05-29",
      "para": "Para 4 (Examination Scheme), Row 3 One Tier (Technical / Teaching), page 30",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29"
  },
  "GJ_GSSSB": {
    "code": "GJ_GSSSB",
    "stage": "Stage 1: Preliminary Examination",
    "questions": 150,
    "marks": 150,
    "durationMin": 120,
    "negativePerWrong": 0.25,
    "sections": [
      {
        "name": "English",
        "questions": null,
        "marks": 15
      },
      {
        "name": "Gujarati",
        "questions": null,
        "marks": 15
      },
      {
        "name": "General Awareness and Current Affairs",
        "questions": null,
        "marks": 30
      },
      {
        "name": "Quantitative Aptitude",
        "questions": null,
        "marks": 30
      },
      {
        "name": "Reasoning",
        "questions": null,
        "marks": 60
      }
    ],
    "languages": "",
    "source": {
      "url": "https://gsssb.gujarat.gov.in/ViewFile?fileName=%E2%9C%BFAv%E2%9C%BFyIFCoiJ6Y3lYByFvHVh8MmeAii5ssTgCCOkn8KmVJNxP3BgxiaCc0G%E2%9C%BFstEl6shK6HWh9Q%E2%9C%BFVe3BGNJvWqxGImhue0J29cbFsjZAobnnoZxQtkq8xRLKWeO%E2%9C%BF1wlObiOQzXmh8KZl8wrFETGcWORA%E2%99%AC%E2%99%AC",
      "publisher": "Gujarat Subordinate Service Selection Board (ગુજરાત ગૌણ સેવા પસંદગી મંડળ), Gandhinagar",
      "publisherShort": "GSSSB",
      "title": "Advt. No. 378/202526 - Gujarat Subordinate Services, Class III (Group-A and Group-B) Combined Competitive Examination -…",
      "publishedOn": "2026-02-03",
      "para": "Para 21 'Examination method', Stage 1, pages 32-33 of 44 of the advertisement dated 03/02/2026",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29"
  },
  "IBPS_CLERK": {
    "code": "IBPS_CLERK",
    "stage": "Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0,
    "negativeText": "one fourth (0.25) of the marks assigned to a question is deducted for each wrong answer",
    "sections": [
      {
        "name": "English Language",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Numerical Ability",
        "questions": 35,
        "marks": 35
      },
      {
        "name": "Reasoning Ability",
        "questions": 35,
        "marks": 35
      }
    ],
    "languages": "English Language test in English; the other two tests in English, Hindi and, in some States/UTs, a regional language",
    "source": {
      "url": "https://www.ibps.in/wp-content/uploads/Notification_CRP_CSA_XVI-Final.pdf",
      "publisher": "Institute of Banking Personnel Selection",
      "publisherShort": "IBPS",
      "title": "Notification: CRP CSA-XVI, Common Recruitment Process for Recruitment of Customer Service Associates (CSA) in…",
      "publishedOn": "2026-08-01",
      "para": "Clause D (Structure of Examination), I(a), printed page 14 (PDF page 17)"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "IBPS_PO": {
    "code": "IBPS_PO",
    "stage": "Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0,
    "negativeText": "one fourth (0.25) of the marks assigned to a question is deducted for each wrong answer; a blank answer has no penalty",
    "marksNote": "Marks do not follow question counts: Quantitative Aptitude has 35 questions for 30 marks, Reasoning Ability 35 for 40, English Language 30 for 30",
    "sections": [
      {
        "name": "English Language",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Quantitative Aptitude",
        "questions": 35,
        "marks": 30
      },
      {
        "name": "Reasoning Ability",
        "questions": 35,
        "marks": 40
      }
    ],
    "languages": "English Language in English; Quantitative Aptitude and Reasoning Ability in English and Hindi",
    "source": {
      "url": "https://www.ibps.in/wp-content/uploads/Detailed-Notification_CRP-PO-XVI_Final_V1_30.06.2026.pdf",
      "publisher": "Institute of Banking Personnel Selection",
      "publisherShort": "IBPS",
      "title": "Notification: Common Recruitment Process (CRP) for Recruitment of Probationary Officers/Management Trainees in…",
      "publishedOn": "2026-07-01",
      "para": "Clause D 'Structure of Examination', (a) Preliminary Examination (Objective Test), notification page 12"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "JH_TET": {
    "code": "JH_TET",
    "stage": "Level-1",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Child Development and Pedagogy (compulsory)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language-I: any two of Hindi, Sanskrit, Urdu and English",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language-II: one regional or tribal language listed in Schedule-I of the Rules",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Environmental Studies",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "Hindi and English (medium Hindi or English); the language papers in their own language",
    "source": {
      "url": "https://jac.jharkhand.gov.in/jac/web_notice/2026_JHTET_NOTIFICATION.pdf",
      "publisher": "Jharkhand Academic Council, Ranchi",
      "publisherShort": "JAC",
      "title": "Jharkhand Teacher Eligibility Test Rules 2026 (Jharkhand Shikshak Patrata Pariksha Niyamavali-2026), Notification No.…",
      "publishedOn": "2026-03-26",
      "para": "Rule 11(ख) duration, 11(ग) multiple-choice and no negative marking, 11(घ) Level-1 table, all on page 10",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "KA_KARTET": {
    "code": "KA_KARTET",
    "stage": "Paper-1",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Language-1 (compulsory)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language-2 (compulsory)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Child Development and Pedagogy (compulsory)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Environmental Studies",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "Kannada, English, Urdu, Tamil, Telugu, Hindi and Marathi, except the language papers",
    "source": {
      "url": "https://schooleducation.karnataka.gov.in/uploads/media_to_upload1760804593.pdf",
      "publisher": "Centralised Admission Cell (CAC), Commissioner's Office, Department of School Education, Government of Karnataka, Bengal",
      "publisherShort": "Karnataka School Education Dept",
      "title": "Karnataka Teacher Eligibility Test - 2025, Notification (Adhisuchane), No. DPI-CPI0CAC(KTET)/4/2025-CAC",
      "publishedOn": "2025-10-18",
      "para": "Notification dated 18/10/2025: para 8.2 (page 7) for questions, marks, options and negative evaluation",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "MH_MPSC_GROUP_C": {
    "code": "MH_MPSC_GROUP_C",
    "stage": "Combined Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0.25,
    "sections": [
      {
        "name": "General Ability Test (subject code 1122)",
        "questions": 100,
        "marks": 100
      }
    ],
    "languages": "Marathi and English",
    "source": {
      "url": "https://mpsc.gov.in/examination_scheme/17",
      "publisher": "Maharashtra Public Service Commission",
      "publisherShort": "MPSC",
      "title": "Maharashtra Group C Services Combined Examination - Revised Scheme of Examination",
      "publishedOn": "2026-05-20",
      "para": "Revised Scheme of Examination dated 20 May 2026, para 6.1.1 (table), page 7 of 10",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "ML_MPSC": {
    "code": "ML_MPSC",
    "stage": "Preliminary Examination, Paper I",
    "questions": 100,
    "marks": 200,
    "durationMin": 120,
    "negativePerWrong": 0,
    "sections": [],
    "languages": "",
    "source": {
      "url": "https://mpsc.meghalaya.gov.in/syllabus/MCS_Syllabus2025.pdf",
      "publisher": "Meghalaya Public Service Commission",
      "publisherShort": "MPSC",
      "title": "Government of Meghalaya, Personnel & A.R. (A) Department, Notification No. PER.6/97/225 - syllabus and pattern of…",
      "publishedOn": "2025-08-11",
      "para": "Marks, duration, objective type: Section II, A. Preliminary Examination, paras (1)-(4) I, page 1 of 3 of…"
    },
    "checkedOn": "2026-09-29"
  },
  "MP_POLICE_PC": {
    "code": "MP_POLICE_PC",
    "stage": "First Stage Written Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 120,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "General Knowledge and Logical Knowledge",
        "questions": null,
        "marks": 40
      },
      {
        "name": "Intellectual Ability and Mental Aptitude",
        "questions": null,
        "marks": 30
      },
      {
        "name": "Science and Simple Arithmetic",
        "questions": null,
        "marks": 30
      }
    ],
    "languages": "Hindi/English medium",
    "source": {
      "url": "https://esb.mp.gov.in/Rulebooks/RB_2026/PCRT_GD_2026_RuleBook_09092026.pdf",
      "publisher": "Madhya Pradesh Employees Selection Board, Bhopal",
      "publisherShort": "MPESB",
      "title": "Departmental Recruitment Rules and Examination Conduct Rule Book for the Selection Examination 2026 for direct…",
      "publishedOn": "",
      "para": "Chapter 1, para (8) Pariksha Yojana and para (9) Pratham Charan Pariksha Yojana, page 8"
    },
    "checkedOn": "2026-09-29"
  },
  "MZ_MPSC": {
    "code": "MZ_MPSC",
    "stage": "Preliminary Examination, Paper-I",
    "questions": 100,
    "marks": 200,
    "durationMin": 120,
    "negativePerWrong": 0,
    "negativeText": "For each question for which a wrong answer is given, one-third of the marks assigned to that question will be deducted as penalty",
    "sections": [
      {
        "name": "Current events of Mizoram, national and international importance",
        "questions": 14,
        "marks": null
      },
      {
        "name": "History of India and Indian national movement",
        "questions": 12,
        "marks": null
      },
      {
        "name": "Indian and World Geography - physical, social, economic geography of India and the world",
        "questions": 12,
        "marks": null
      },
      {
        "name": "Indian polity and governance - Constitution, political system, panchayati raj, public…",
        "questions": 12,
        "marks": null
      },
      {
        "name": "Economic and social development - sustainable development, poverty, inclusion,…",
        "questions": 12,
        "marks": null
      },
      {
        "name": "General issues on environmental ecology, bio-diversity and climate change that do not…",
        "questions": 12,
        "marks": null
      },
      {
        "name": "General Science",
        "questions": 12,
        "marks": null
      },
      {
        "name": "General Awareness on Mizo Society, its culture and heritage",
        "questions": 14,
        "marks": null
      }
    ],
    "languages": "",
    "source": {
      "url": "https://mpsc.mizoram.gov.in/uploads/attachments/2025/08/d89bfbc71ea5cda75b0957627c877416/scheme-of-examination-for-mizoram-civil-services-combined-competitive-examination-2025.pdf",
      "publisher": "Mizoram Public Service Commission",
      "publisherShort": "MPSC",
      "title": "Notification No.A.12034/18/2025-MPSC(EXAM): Scheme of Examination for Mizoram Civil Services (Combined Competitive)…",
      "publishedOn": "2025-08-27",
      "para": "Scheme notification of 27 Aug 2025, Part A 'Preliminary Examination', items (a) Time Allowed, (b) Maximum…",
      "scanned": true
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "NSTSE": {
    "code": "NSTSE",
    "stage": "Classes 6 to 10 question paper",
    "questions": 60,
    "marks": 60,
    "durationMin": 60,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Physics",
        "questions": null,
        "marks": 15
      },
      {
        "name": "Chemistry",
        "questions": null,
        "marks": 15
      },
      {
        "name": "Biology",
        "questions": null,
        "marks": 15
      },
      {
        "name": "Mathematics",
        "questions": null,
        "marks": 10
      },
      {
        "name": "Critical Thinking",
        "questions": null,
        "marks": 5
      }
    ],
    "languages": "English only",
    "source": {
      "url": "https://www.unifiedcouncil.com/about-nstse.html",
      "publisher": "Unified Council",
      "publisherShort": "Unified Council",
      "title": "About NSTSE - 'NSTSE EXAM PATTERN' (National Level Science Talent Search Examination), 2026-27 cycle",
      "publishedOn": "",
      "para": "'NSTSE EXAM PATTERN' panel and 'Division of marks in the Question Paper : For Classes 6 to 10', About NSTSE…"
    },
    "checkedOn": "2026-09-29"
  },
  "RJ_REAP": {
    "code": "RJ_REAP",
    "stage": "JEE (Main) Paper 1",
    "questions": 75,
    "marks": 300,
    "durationMin": 180,
    "negativePerWrong": 1,
    "answerFormat": "Section A: Multiple-Choice Questions. Section B: enter the correct integer value using the on-screen virtual numeric keypad, rounded off to the nearest integer",
    "practiceFormatDiffers": true,
    "sections": [
      {
        "name": "Mathematics (Section A: 20 questions, Section B: 5 questions)",
        "questions": null,
        "marks": 100
      },
      {
        "name": "Physics (Section A: 20 questions, Section B: 5 questions)",
        "questions": null,
        "marks": 100
      },
      {
        "name": "Chemistry (Section A: 20 questions, Section B: 5 questions)",
        "questions": null,
        "marks": 100
      }
    ],
    "languages": "",
    "source": {
      "url": "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2025/11/202511021649722475.pdf",
      "publisher": "National Testing Agency",
      "publisherShort": "NTA",
      "title": "Information Bulletin - 2026, Joint Entrance Examination (Main) - 2026",
      "publishedOn": "",
      "para": "Chapter 2 Examination Scheme: para 2.4 Pattern of Examination, Paper 1, items 1-3"
    },
    "checkedOn": "2026-09-29"
  },
  "RJ_RPSC_RAS": {
    "code": "RJ_RPSC_RAS",
    "stage": "Preliminary Examination",
    "questions": 150,
    "marks": 200,
    "durationMin": 180,
    "negativePerWrong": 0.3333333333333333,
    "negativeText": "1/3 mark is deducted for each wrong answer, and 1/3 of the question's marks if none of the five circles is darkened",
    "sections": [],
    "languages": "",
    "source": {
      "url": "https://rpsc.rajasthan.gov.in/Static/RecruitmentAdvertisements/76C02A7D61A54708AFFCDD7A2A60DBB2.pdf",
      "publisher": "Rajasthan Public Service Commission, Ajmer",
      "publisherShort": "RPSC",
      "title": "Detailed Advertisement No. 02/Exam/RAS&RTS/RPSC/EP-I/2026-27 for Rajasthan State and Subordinate Services Combined…",
      "publishedOn": "2026-05-27",
      "para": "Scheme & Syllabus of Examination (Preliminary) dated 09-01-2026, page 1: scheme paragraph, subject table,…",
      "kind": "advertisement",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "RJ_RSMSSB": {
    "code": "RJ_RSMSSB",
    "stage": "Common Eligibility Test",
    "questions": 150,
    "marks": 300,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeText": "There will be negative marking of one-third (1/3) of the total marks for each wrong answer",
    "sections": [],
    "languages": "",
    "source": {
      "url": "https://rssb.rajasthan.gov.in/storage/advertisement_item/1782966142.pdf",
      "publisher": "Rajasthan Staff Selection Board (राजस्थान कर्मचारी चयन बोर्ड), formerly Rajasthan Subordinate and Ministerial Services S",
      "publisherShort": "RSSB",
      "title": "Advertisement No. 09/2026 (विज्ञापन सं. 09/2026), Common Eligibility Test (Graduation Level)-2026, Detailed…",
      "publishedOn": "2026-07-01",
      "para": "Para 17, 'Scheme of the Examination' (परीक्षा की स्कीम) table and notes, page 15 of 24",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "SBI_CLERK": {
    "code": "SBI_CLERK",
    "stage": "Phase-I: Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0,
    "negativeText": "1/4th of the mark assigned to a question is deducted for each wrong answer",
    "sections": [
      {
        "name": "English language",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Numerical Ability",
        "questions": 35,
        "marks": 35
      },
      {
        "name": "Reasoning Ability",
        "questions": 35,
        "marks": 35
      }
    ],
    "languages": "English Language test in English; the other two tests in English, Hindi and, in some States/UTs, a regional language",
    "source": {
      "url": "https://sbi.bank.in/webfiles/uploads/files_2627/08/JA_2026_Detailed_Advt_Eng.pdf",
      "publisher": "State Bank of India",
      "publisherShort": "SBI",
      "title": "Recruitment of Junior Associates (Customer Support & Sales) - Advertisement No. CRPD/CR/2026-27/17",
      "publishedOn": "2026-08-11",
      "para": "Advertisement para 4 'Selection Procedure', Phase-I: Preliminary Examination, page 5 of 11",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "TN_TNPSC_GROUP2": {
    "code": "TN_TNPSC_GROUP2",
    "stage": "Preliminary Examination",
    "questions": 200,
    "marks": 300,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "negativeText": "no deduction printed for a wrong answer; 0.5 mark is deducted if a question is left blank",
    "sections": [
      {
        "name": "A. General Studies (Degree Standard)",
        "questions": 75,
        "marks": null
      },
      {
        "name": "B. Aptitude and Mental Ability (SSLC Standard)",
        "questions": 25,
        "marks": null
      },
      {
        "name": "C. Language (General Tamil or General English) (SSLC Standard)",
        "questions": 100,
        "marks": null
      }
    ],
    "languages": "General Studies in Tamil and English; the language part is General Tamil or General English",
    "source": {
      "url": "https://tnpsc.gov.in/document/english/07_2026%20Dated_11.08.2026%20English%20version.pdf",
      "publisher": "Tamil Nadu Public Service Commission",
      "publisherShort": "TNPSC",
      "title": "Combined Civil Services Examination - II (Group II and IIA Services) - Notification No. 07/2026 (Advertisement No. 740)",
      "publishedOn": "2026-08-11",
      "para": "Para 6.1 Preliminary Examination (Single Paper), Scheme of Examination table, page 19 of 87"
    },
    "checkedOn": "2026-09-29"
  },
  "TN_TNPSC_GROUP4": {
    "code": "TN_TNPSC_GROUP4",
    "stage": "Written Examination",
    "questions": 200,
    "marks": 300,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "negativeText": "no deduction printed for a wrong answer; 0.5 mark is deducted if a question is left blank",
    "marksNote": "Part A has 100 questions for 150 marks; Parts B and C (75 + 25 questions) share one maximum of 150",
    "sections": [
      {
        "name": "Part A: Tamil Eligibility-cum-Scoring Test (SSLC Standard)",
        "questions": 100,
        "marks": 150
      },
      {
        "name": "Part B: General Studies (SSLC Standard)",
        "questions": 75,
        "marks": null
      },
      {
        "name": "Part C: Aptitude and Mental Ability (SSLC Standard)",
        "questions": 25,
        "marks": null
      }
    ],
    "languages": "Part A (Tamil Eligibility-cum-Scoring Test) set in Tamil only; Part B and Part C set both in Tamil and English",
    "source": {
      "url": "https://tnpsc.gov.in/document/english/Grp%20IV%20English_.pdf",
      "publisher": "Tamil Nadu Public Service Commission",
      "publisherShort": "TNPSC",
      "title": "Combined Civil Services Examination - IV (Group IV Services) - Notification No. 07/2025 (Advertisement No.709), read…",
      "publishedOn": "2025-04-25",
      "para": "Para 6 Scheme of Examination (table) and para 6.1, page 19 of 72"
    },
    "checkedOn": "2026-09-29"
  },
  "TN_TNUSRB_SI": {
    "code": "TN_TNUSRB_SI",
    "stage": "Main Written Examination",
    "questions": 140,
    "marks": 70,
    "durationMin": 150,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "sections": [
      {
        "name": "Part-A - General Knowledge",
        "questions": 80,
        "marks": 40
      },
      {
        "name": "Part-B - Psychology Test",
        "questions": 60,
        "marks": 30
      }
    ],
    "languages": "",
    "source": {
      "url": "https://tnusrb.tn.gov.in/pdfs/SI(TK,%20AR)%202025%20Notification_n.pdf",
      "publisher": "Tamil Nadu Uniformed Services Recruitment Board",
      "publisherShort": "TNUSRB",
      "title": "Notification No: 01/2025 - Direct Recruitment for the posts of Sub-Inspectors of Police - 2025 [Taluk & Armed Reserve…",
      "publishedOn": "2025-04-04",
      "para": "Notification No. 01/2025, para 16 (A) Written Examination, Part-II Main Written Examination, items i-v, page…"
    },
    "checkedOn": "2026-09-29"
  },
  "TS_POLICE_PC": {
    "code": "TS_POLICE_PC",
    "stage": "Preliminary Written Test",
    "questions": 200,
    "marks": 200,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeText": "a wrong answer, or more than one bubble darkened, is marked minus 20% of the question's full marks; a question left blank gets zero",
    "sections": [],
    "languages": "English-Telugu and English-Urdu versions",
    "source": {
      "url": "https://doc.tgprb.in/PC+(Civil+et+al)+2026+Notification+dated+29-07-2026.pdf",
      "publisher": "Telangana State Level Police Recruitment Board",
      "publisherShort": "TSLPRB",
      "title": "Notification Rc No. 189 / Rect. / Rect.2 / 2026 - SCT Police Constable (Civil) and / or equivalent Posts",
      "publishedOn": "2026-07-29",
      "para": "Para 16 (Selection Procedure / Scheme), sub-para A, page 25 of 57"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "TS_POLICE_SI": {
    "code": "TS_POLICE_SI",
    "stage": "Preliminary Written Test",
    "questions": 200,
    "marks": 200,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeText": "a wrong answer, or more than one bubble darkened, is marked minus 20% of the question's full marks; a question left blank gets zero",
    "sections": [
      {
        "name": "Arithmetic and Test of Reasoning / Mental Ability",
        "questions": 100,
        "marks": null
      },
      {
        "name": "General Studies",
        "questions": 100,
        "marks": null
      }
    ],
    "languages": "English-Telugu and English-Urdu versions",
    "source": {
      "url": "https://doc.tgprb.in/SI+(Civil+et+al)+2026+Notification+dated+29-07-2026.pdf",
      "publisher": "Telangana State Level Police Recruitment Board",
      "publisherShort": "TSLPRB",
      "title": "Notification Rc. No. 225 / Rect. / Rect.1 / 2026 - direct recruitment to SCT Sub Inspector of Police (Civil) and…",
      "publishedOn": "2026-07-29",
      "para": "Para 16 (A), Selection Procedure / Scheme: opening lines on page 19, scheme table and Notes 1-5 on page 20 of…"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "TS_TSPSC_GROUP1": {
    "code": "TS_TSPSC_GROUP1",
    "stage": "Preliminary Test",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "sections": [],
    "languages": "English, Telugu and Urdu",
    "source": {
      "url": "https://websitenew.tgpsc.gov.in/preview/RElSRUNUUkVDUlVJVE1FTlROT1RJL05PVElGSUNBVElPTl9OT18wMi0yMDI0X0dyb3VwLUlfU2VydmljZXMgKDEpMjAyNDAyMjAxNDA3MzcucGRmr95v17a0y2d8i13v",
      "publisher": "Telangana State Public Service Commission (now Telangana Public Service Commission)",
      "publisherShort": "TSPSC",
      "title": "Notification No. 02/2024, dated 19/02/2024 - Group-I Services (General Recruitment)",
      "publishedOn": "2024-02-19",
      "para": "Para 9 (page 14) prescribes the scheme as per G.O. Ms. No. 55 GA (Ser.A) Dt.25/04/2022 as amended by G.O. Ms.…"
    },
    "checkedOn": "2026-09-29"
  },
  "TS_TSPSC_GROUP3": {
    "code": "TS_TSPSC_GROUP3",
    "stage": "Paper-I",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "sections": [],
    "languages": "English, Telugu and Urdu",
    "source": {
      "url": "https://websitenew.tgpsc.gov.in/preview/RElSRUNUUkVDUlVJVE1FTlROT1RJLzI5LTIwMjItR1JPVVAtSUlJLTIwMjIyMDIzMDEyNDE5NDgyOC5wZGY=r95v17a0y2d8i13v",
      "publisher": "Telangana State Public Service Commission",
      "publisherShort": "TSPSC",
      "title": "Notification No. 29/2022, Group-III Services (General Recruitment), Telangana State Public Service Commission",
      "publishedOn": "2022-12-30",
      "para": "Annexure-III, Scheme of Examination, page 55 (PARA-VII on page 14 points to it)"
    },
    "checkedOn": "2026-09-29"
  },
  "UK_UKPSC_PCS": {
    "code": "UK_UKPSC_PCS",
    "stage": "Preliminary Examination, First Paper",
    "questions": 150,
    "marks": 150,
    "durationMin": 120,
    "negativePerWrong": 0.25,
    "sections": [],
    "languages": "",
    "source": {
      "url": "https://psc.uk.gov.in/public/uploads/recruitment/1843959203.pdf",
      "publisher": "Uttarakhand Public Service Commission",
      "publisherShort": "UKPSC",
      "title": "Advertisement No. A-1/E-1/2026-27: Uttarakhand Combined State Civil/Upper Subordinate Services Examination-2026",
      "publishedOn": "2026-09-09",
      "para": "Annexure-2, section '1",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29"
  },
  "UP_POLICE_CONSTABLE": {
    "code": "UP_POLICE_CONSTABLE",
    "stage": "Written Examination",
    "questions": 150,
    "marks": 300,
    "durationMin": 120,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "sections": [],
    "languages": "Hindi and English, except General Hindi; the English version prevails in case of doubt",
    "source": {
      "url": "https://uppbpb.gov.in/FilesUploaded/Notice/CONST-25OMRVIGGYAPTI05-02-2026590e47bd-d973-4a45-9007-b2a0a048b4f4.pdf",
      "publisher": "Uttar Pradesh Police Recruitment and Promotion Board",
      "publisherShort": "UPPRPB",
      "title": "UP Police Constable Civil Police and Equivalent Posts Direct Recruitment-2025: Written Examination Process and OMR…",
      "publishedOn": "2026-02-05",
      "para": "Notice of 05-02-2026, paras 1, 2, 4 and 6 (pages 1-2) and para 16 (page 3)",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "UP_POLICE_SI": {
    "code": "UP_POLICE_SI",
    "stage": "Written Examination",
    "questions": 160,
    "marks": 400,
    "durationMin": 120,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "sections": [
      {
        "name": "General Hindi",
        "questions": 40,
        "marks": 100
      },
      {
        "name": "Basic Law / Constitution / General Knowledge",
        "questions": 40,
        "marks": 100
      },
      {
        "name": "Numerical and Mental Ability Test",
        "questions": 40,
        "marks": 100
      },
      {
        "name": "Mental Aptitude Test / Intelligence Test / Reasoning Test",
        "questions": 40,
        "marks": 100
      }
    ],
    "languages": "Hindi and English for all subjects except General Hindi; the English version prevails in case of doubt",
    "source": {
      "url": "https://uppbpb.gov.in/FilesUploaded/Notice/VK-SI-omr-nOTICE11d5a429-62f9-46d6-b01c-0957d21b2919.pdf",
      "publisher": "Uttar Pradesh Police Recruitment and Promotion Board",
      "publisherShort": "UPPRPB",
      "title": "SI Civil Police and Equivalent Posts Direct Recruitment-2025: publication of the written examination process and OMR…",
      "publishedOn": "2026-01-14",
      "para": "Notice dated 14 Jan 2026, paras 1-6 and 16, pages 1-3",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "UP_UPTET": {
    "code": "UP_UPTET",
    "stage": "Paper I - Primary Level",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Child Development and Teaching Methods",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language I (Hindi)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language II (English / Urdu / Sanskrit)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Environmental Studies",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "Hindi and English (except the language subjects)",
    "source": {
      "url": "https://upessc.up.gov.in/Advertisment/ef95e113-7ed8-4e56-99d3-50952353009d.pdf",
      "publisher": "Uttar Pradesh Education Service Selection Commission",
      "publisherShort": "UPESSC",
      "title": "Uttar Pradesh Teacher Eligibility Test (UPTET)-2026, Adv. No. 01/UPTET/2026, Information Booklet",
      "publishedOn": "2026-03-20",
      "para": "Para 7 (Scheme of Examination and Syllabus) table, booklet page 4 of 9 (PDF page 7)",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29"
  },
  "WB_TET": {
    "code": "WB_TET",
    "stage": "TET-2023 (For Primary)",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Part A: Child Development and Pedagogy",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Part B: Language I (Bengali/Hindi/Oriya/Telugu/Nepali/Santhali/Urdu)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Part C: Language II (English)",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Part D: Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Part E: Environmental Studies",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "Bilingual (Bengali and English), except the Language I and Language II parts",
    "source": {
      "url": "https://wbbpe.wb.gov.in/file/INFORMATION_PART-WISE_MODEL_QUESTIONS_TET-2023_16102023.pdf",
      "publisher": "West Bengal Board of Primary Education",
      "publisherShort": "WBBPE",
      "title": "Relevant Information and Part-wise Model Questions for Teacher Eligibility Test-2023 (TET-2023) (For Primary)",
      "publishedOn": "",
      "para": "'Structure and Content' table and the three notes below it, page 1 of the 9-page information bulletin for…"
    },
    "checkedOn": "2026-09-29"
  }
};

export const READ_DOCUMENTS: Readonly<Record<string, SyllabusDocument>> = {
  "AP_APPSC_GROUP1": {
    "publisherShort": "APPSC",
    "name": "Annexure to Brief Notification No.07/2026: Scheme and Syllabus for Recruitment to the Posts falling under…",
    "url": "https://psc.ap.gov.in/Documents/NotificationDocuments/Group_I_072026.pdf",
    "readOn": "2026-09-29"
  },
  "AP_APPSC_GROUP3": {
    "publisherShort": "APPSC",
    "name": "Annexure-II: Scheme and Syllabus for Recruitment to the Post of Panchayat Secretary (Grade-IV) in A.P.…",
    "url": "https://psc.ap.gov.in/UserManuals/LatestNotifications/13_2018.pdf",
    "readOn": "2026-09-29"
  },
  "AP_TET": {
    "publisherShort": "CSE AP",
    "name": "Suggestive Syllabus for APTET - JUNE - 2026 (Government of Andhra Pradesh, Department of School Education)",
    "url": "https://tet2dsc.apcfss.in/TET-PDF/APTET%202026%20Syllabus%201.pdf",
    "readOn": "2026-09-29"
  },
  "AS_TET": {
    "publisherShort": "SSA Assam",
    "name": "Syllabus for Special TET, 2026 - Language II (English), Paper I (For Classes I-V), Total Marks: 30",
    "url": "https://ssa.assam.gov.in/sites/default/files/swf_utility_folder/departments/ssam_medhassu_in_oid_5/latest/paper_i_language_ii_english.pdf",
    "readOn": "2026-09-29"
  },
  "BR_BPSC_CCE": {
    "publisherShort": "BPSC",
    "name": "Bihar Gazette (Extraordinary), Patna, 23 August 2017: updated structure and syllabus of the BPSC Combined…",
    "url": "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Syllabus/Syllabus-CC-Exam-Updated_20250410_092923_d897d7c5.pdf",
    "readOn": "2026-09-29"
  },
  "CDS": {
    "publisherShort": "UPSC",
    "name": "Appendix-I, Part B 'Standard and Syllabus of the Examination' in Examination Notice No. 11/2026-CDS-II",
    "url": "https://www.upsc.gov.in/sites/default/files/Notif-CDS-II-2026-Engl-200526.pdf",
    "readOn": "2026-09-29",
    "caveat": "The syllabus is printed inside the examination notice."
  },
  "CG_CGPSC_SSE": {
    "publisherShort": "CGPSC",
    "name": "Annexure-II 'State Service Preliminary Examination' paper-wise syllabus, in Advertisement No. 06/2025/Exam…",
    "url": "https://psc.cg.gov.in/PDFs/advertisement/STATE_SERVICE_EXAMINATION-2025_ADVERTISEMENT%20(26-11-2025).pdf",
    "readOn": "2026-09-29"
  },
  "CTET": {
    "publisherShort": "CBSE",
    "name": "Appendix-I, Structure and Content of Syllabus (Paper I and Paper II), in the Information Bulletin…",
    "url": "https://cdnbbsr.s3waas.gov.in/s3443dec3062d0286986e21dc0631734c9/uploads/2026/05/202605111250310617.pdf",
    "readOn": "2026-09-29"
  },
  "DL_DSSSB_TGT": {
    "publisherShort": "DSSSB",
    "name": "SYLLABUS: I-T-T One Tier (Technical / Teaching) 200 Marks",
    "url": "https://dsssb.delhi.gov.in/sites/default/files/DSSSB/universal-tab/syllabus_i-t-t_one_tier_technical_i_teaching_200_marks.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "GJ_GSSSB": {
    "publisherShort": "GSSSB",
    "name": "Advt. 378/202526 - Combined Competitive Examination, Stage 1: Preliminary Exam detailed syllabus",
    "url": "https://gsssb.gujarat.gov.in/ViewFile?fileName=4naZ%E2%9C%BF8wS64TzwZ61AZrbMP4tvDBt3Mj8UPSd1xKcshtZxTB5t5ltTF2mrczYtutOJGDlDeTKGm0IBe3QAs0YsAvhcBHVUA7rWLv6ae41Hda0d6MmkmlJGOJcCYvEzD6nnekULO9MvmUb8i9F7qJMxg%E2%99%AC%E2%99%AC",
    "readOn": "2026-09-29"
  },
  "HR_TET": {
    "publisherShort": "BSEH",
    "name": "Haryana Teacher Eligibility Test-2024 Information Bulletin, Annexure-I: Content of Syllabus for Level-I,…",
    "url": "https://bseh.org.in/uploads/files/3d7b5cf7d6d3c91133a80e9ef3fbfae9.pdf",
    "readOn": "2026-09-29"
  },
  "JH_TET": {
    "publisherShort": "JAC",
    "name": "JHTET Examination 2026 Syllabus (Jharkhand Shikshak Patrata Pariksha 2026 Pathyakram), both levels, posted by…",
    "url": "https://jac.jharkhand.gov.in/jac/web_notice/2026_JHTET_SYLLABUS.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "KA_KARTET": {
    "publisherShort": "Karnataka School Education Dept",
    "name": "KARTET-2025 Syllabus (Pathyakrama), subject-wise for Paper-1 and Paper-2, linked as '2. Syllabus' under the…",
    "url": "https://schooleducation.karnataka.gov.in/uploads/media_to_upload1760804671.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "KA_KCET": {
    "publisherShort": "KEA",
    "name": "UGCET - 2026 Syllabus 29-01-2026",
    "url": "https://cetonline.karnataka.gov.in/keawebentry456/ugcet2026/PHYSICS_SYB_29012026english.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "KA_KPSC_KAS": {
    "publisherShort": "KPSC",
    "name": "Syllabus for Gazetted Probationers Exam",
    "url": "https://kpsc.kar.nic.in/syll_GP.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "MH_MPSC_GROUP_C": {
    "publisherShort": "MPSC",
    "name": "Maharashtra Group-C Services Combined Preliminary Examination - Syllabus",
    "url": "https://mpsc.gov.in/examination_syllabus/18",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "ML_MPSC": {
    "publisherShort": "MPSC",
    "name": "Syllabus for the Meghalaya Civil Service - Notification No. PER.6/97/225 dated 11 August 2025, Section II A",
    "url": "https://mpsc.meghalaya.gov.in/syllabus/MCS_Syllabus2025.pdf",
    "readOn": "2026-09-29"
  },
  "MP_RAEO": {
    "publisherShort": "MP-ESB",
    "name": "Chapter 04: Syllabus (Pathyakram), Krishi Vistar Adhikari Recruitment Test - 2026, in the same rule book",
    "url": "https://esb.mp.gov.in/Rulebooks/RB_2026/Group2_SG1_RuleBook_2026_02072026.pdf",
    "readOn": "2026-09-29"
  },
  "MZ_MPSC": {
    "publisherShort": "MPSC",
    "name": "Mizoram Civil Services (Combined Competitive Examination) Rules, 2025 - Schedule-I: Scheme and Syllabus for…",
    "url": "https://mpsc.mizoram.gov.in/uploads/attachments/2026/04/de7d05fc97a84c398208444a121c9249/mizoram-civil-servicescombined-competitive-examination-rules-2025.pdf",
    "readOn": "2026-09-29"
  },
  "NDA": {
    "publisherShort": "UPSC",
    "name": "Appendix-I, Part B 'Syllabus of the Examination' in Examination Notice No. 10/2026-NDA-II",
    "url": "https://www.upsc.gov.in/sites/default/files/Notif-NDA-II-2026-Engl-200526.pdf",
    "readOn": "2026-09-29",
    "caveat": "The syllabus is printed inside the examination notice."
  },
  "NSEA": {
    "publisherShort": "IAPT",
    "name": "Syllabus for National Standard Examination and Indian National Olympiad in Physics, Chemistry, Biology,…",
    "url": "https://iapt.org.in/wp-content/uploads/images/syllabus-for-nse-ino-2022-2023.pdf",
    "readOn": "2026-09-29"
  },
  "NSEB": {
    "publisherShort": "IAPT",
    "name": "Syllabus for National Standard Examination and Indian National Olympiad in Physics, Chemistry, Biology,…",
    "url": "https://iapt.org.in/wp-content/uploads/images/syllabus-for-nse-ino-2022-2023.pdf",
    "readOn": "2026-09-29"
  },
  "NSEC": {
    "publisherShort": "IAPT",
    "name": "Syllabus for National Standard Examination and Indian National Olympiad in Physics, Chemistry, Biology,…",
    "url": "https://iapt.org.in/wp-content/uploads/images/syllabus-for-nse-ino-2022-2023.pdf",
    "readOn": "2026-09-29"
  },
  "NSEJS": {
    "publisherShort": "IAPT",
    "name": "Syllabus for National Standard Examination and Indian National Olympiad in Physics, Chemistry, Biology,…",
    "url": "https://iapt.org.in/wp-content/uploads/images/syllabus-for-nse-ino-2022-2023.pdf",
    "readOn": "2026-09-29",
    "caveat": "The file is titled 2022-2023; IAPT's site links it as the syllabus for NSE 2026-27."
  },
  "NSTSE": {
    "publisherShort": "Unified Council",
    "name": "National Science Talent Search Examination - Syllabus (Classes 1 to 10)",
    "url": "https://www.unifiedcouncil.com/documents/syllabus/NSTSE-Syllabus.pdf",
    "readOn": "2026-09-29"
  },
  "RJ_RPSC_RAS": {
    "publisherShort": "RPSC",
    "name": "Rajasthan State and Subordinate Services Combined Competitive (Preliminary) Examination: Scheme & Syllabus of…",
    "url": "https://rpsc.rajasthan.gov.in/Static/Syllabus/7D943B35-2D9E-4E50-BC3E-3726268AE18B.pdf",
    "readOn": "2026-09-29"
  },
  "RJ_RSMSSB": {
    "publisherShort": "RSSB",
    "name": "Syllabus (पाठ्यक्रम विवरण) of CET (Graduation Level)-2026, printed in para 17 of Advertisement No. 09/2026,…",
    "url": "https://rssb.rajasthan.gov.in/storage/advertisement_item/1782966142.pdf",
    "readOn": "2026-09-29"
  },
  "RRB_GROUP_D": {
    "publisherShort": "RRB",
    "name": "CEN No. 09/2025, Para 14.1 'Question Type and Syllabus'",
    "url": "https://rrb.indianrailways.gov.in/-/image/1785986914371examsDocuments.pdf/examsDocuments",
    "readOn": "2026-09-29"
  },
  "SSC_CHSL": {
    "publisherShort": "SSC",
    "name": "Indicative Syllabus (Tier-I), para 13.10 of the Notice of Combined Higher Secondary (10+2) Level Examination,…",
    "url": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_adv_chsle_2026.pdf",
    "readOn": "2026-09-29"
  },
  "SSC_GD": {
    "publisherShort": "SSC",
    "name": "Indicative syllabus, para 12.1.11 of the Notice of Constable (GD) in CAPFs and SSF, and Rifleman (GD) in…",
    "url": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_CTGD_2026.pdf",
    "readOn": "2026-09-29"
  },
  "TN_TNPSC_GROUP2": {
    "publisherShort": "TNPSC",
    "name": "Combined Civil Services (Preliminary) Examination - II (Group II and IIA Services) - Syllabus, Code: 495",
    "url": "https://tnpsc.gov.in/static_pdf/syllabus/495_Group%20II%20and%20IIA%20prelims.pdf",
    "readOn": "2026-09-29"
  },
  "TN_TNPSC_GROUP4": {
    "publisherShort": "TNPSC",
    "name": "Annexure III - Syllabus (Code: 496) of Notification No.07/2025, pages 55 to 58 of 72",
    "url": "https://tnpsc.gov.in/document/english/Grp%20IV%20English_.pdf",
    "readOn": "2026-09-29"
  },
  "TN_TNUSRB_SI": {
    "publisherShort": "TNUSRB",
    "name": "Syllabus for Written Examination - Sub-Inspectors of Police (Taluk & AR) - 2025",
    "url": "https://tnusrb.tn.gov.in/pdfs/SI_2025_Syllabus.pdf",
    "readOn": "2026-09-29"
  },
  "TS_EAMCET": {
    "publisherShort": "JNTUH",
    "name": "Syllabus for TG EAPCET 2026-A&P Stream (Agriculture, Pharmacy, Veterinary etc.)",
    "url": "https://eapcet.tgche.ac.in/TGEAPCET/Doc2026/Syllabus-AP.pdf",
    "readOn": "2026-09-29"
  },
  "TS_POLICE_SI": {
    "publisherShort": "TSLPRB",
    "name": "Annexure II - Syllabus for Preliminary Written Test (200 Questions - 200 Marks), in Notification Rc. No. 225…",
    "url": "https://doc.tgprb.in/SI+(Civil+et+al)+2026+Notification+dated+29-07-2026.pdf",
    "readOn": "2026-09-29"
  },
  "TS_TSPSC_GROUP1": {
    "publisherShort": "TSPSC",
    "name": "Annexure-II, Scheme and Syllabus for Recruitment to the Posts of Group-I Services",
    "url": "https://websitenew.tgpsc.gov.in/preview/RElSRUNUUkVDUlVJVE1FTlROT1RJL05PVElGSUNBVElPTl9OT18wMi0yMDI0X0dyb3VwLUlfU2VydmljZXMgKDEpMjAyNDAyMjAxNDA3MzcucGRmr95v17a0y2d8i13v",
    "readOn": "2026-09-29"
  },
  "TS_TSPSC_GROUP2": {
    "publisherShort": "TGPSC",
    "name": "Scheme and Syllabus for Recruitment to the Posts of Group-II Services",
    "url": "https://websitenew.tgpsc.gov.in/preview/UFJFU1NOT1RFL0dyb3VwLUlJIFNjaGVtZSBhbmQgU3lsbGFidXMyMDIyMTIzMDE0Mzg0NC5wZGY=r95v17a0y2d8i13v",
    "readOn": "2026-09-29"
  },
  "TS_TSPSC_GROUP3": {
    "publisherShort": "TSPSC",
    "name": "Scheme and Syllabus for Recruitment to the Posts of Group-III Services",
    "url": "https://websitenew.tgpsc.gov.in/preview/UFJFU1NOT1RFL0dyb3VwLUlJSSBTY2hlbWUgYW5kIFN5bGxhYnVzMjAyMzAxMDIxMzEyMTgucGRmr95v17a0y2d8i13v",
    "readOn": "2026-09-29"
  },
  "UK_TET": {
    "publisherShort": "UBSE",
    "name": "Structure and Content of Syllabus - UTET I (classes I to V) and UTET II (classes VI to VIII), listed by the…",
    "url": "https://cdnbbsr.s3waas.gov.in/s32dbf21633f03afcf882eaf10e4b5caca/uploads/2025/07/202507111495469767.pdf",
    "readOn": "2026-09-29",
    "scanned": true,
    "caveat": "The pages print no date; UBSE's site lists them for UTET."
  },
  "UK_UKPSC_PCS": {
    "publisherShort": "UKPSC",
    "name": "Annexure-2 of Advertisement A-1/E-1/2026-27: Uttarakhand Combined State (Civil) Upper Sub-ordinate…",
    "url": "https://psc.uk.gov.in/public/uploads/recruitment/1843959203.pdf",
    "readOn": "2026-09-29"
  },
  "UPSC_PRELIMS": {
    "publisherShort": "UPSC",
    "name": "Examination Notice No. 05/2026-CSE, Appendix I, Section III: Syllabi for the Examination, Part A: Preliminary…",
    "url": "https://www.upsc.gov.in/sites/default/files/Notif-CSP-2026-Engl-060226Rev.pdf",
    "readOn": "2026-09-29"
  },
  "UP_POLICE_CONSTABLE": {
    "publisherShort": "UPPRPB",
    "name": "Appendix-1: Syllabus of the Written Examination, in the UPPRPB Advertisement for Constable Civil Police and…",
    "url": "https://uppbpb.gov.in/FilesUploaded/Notice/CONSTABLE-VIGYAPTIc7be0cc8-3365-471e-9237-447c528d341a.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "UP_POLICE_SI": {
    "publisherShort": "UPPRPB",
    "name": "Appendix-1: Syllabus of the written examination (लिखित परीक्षा का पाठ्यक्रम), in advertisement no. PRPB-B (SI…",
    "url": "https://uppbpb.gov.in/FilesUploaded/Notice/SI_vigyapti_202567e84cf2-8d04-4072-bdbc-56f3c8e1ccbe.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "UP_UPTET": {
    "publisherShort": "UPESSC",
    "name": "UPTET-2026 syllabus, Annexure-5 of the Information Booklet (Adv. No. 01/UPTET/2026): Paper I Primary Level…",
    "url": "https://upessc.up.gov.in/Advertisment/ef95e113-7ed8-4e56-99d3-50952353009d.pdf",
    "readOn": "2026-09-29"
  },
  "WB_TET": {
    "publisherShort": "WBBPE",
    "name": "Relevant Information and Part-wise Model Questions for Teacher Eligibility Test-2023 (TET-2023) (For…",
    "url": "https://wbbpe.wb.gov.in/file/INFORMATION_PART-WISE_MODEL_QUESTIONS_TET-2023_16102023.pdf",
    "readOn": "2026-09-29"
  }
};

/** "{EXAM}/{topic.code}" → the document's key and the place in it. */
export const READ_PLACES: Readonly<Record<string, { doc: string; where: string }>> = {
  "AP_APPSC_GROUP1/mental_ability.logical_reasoning.series": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 2 (page 9)"
  },
  "AP_APPSC_GROUP1/mental_ability.data_interpretation": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 15 (page 9)"
  },
  "AP_APPSC_GROUP1/mental_ability.logical_reasoning": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 1 (page 9)"
  },
  "AP_APPSC_GROUP1/quant.time_work": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 11 (page 9)"
  },
  "AP_APPSC_GROUP3/gs.logical_reasoning": {
    "doc": "AP_APPSC_GROUP3",
    "where": "Screening Test Part-A: General Studies and Mental Ability, item 10; also Main Paper-I, item 10"
  },
  "AP_TET/aptet.ms.chemistry.elements": {
    "doc": "AP_TET",
    "where": "Paper-II(A), D.1 Mathematics and Science, D.1.2 Physical Science (Content), Unit 15: Matter"
  },
  "AS_TET/lang2.tense": {
    "doc": "AS_TET",
    "where": "Paper I, Language II (English), Grammar (10 marks), item 3"
  },
  "BR_BPSC_CCE/bihar.1857_revolt": {
    "doc": "BR_BPSC_CCE",
    "where": "Main Examination, General Studies Paper I: Modern History of India and Indian Culture"
  },
  "CDS/math.geometry": {
    "doc": "CDS",
    "where": "Elementary Mathematics (Code No. 13), heading Geometry, page 20"
  },
  "CG_CGPSC_SSE/gs.geog.indian": {
    "doc": "CG_CGPSC_SSE",
    "where": "Paper 1 General Studies, Part 1: General Studies, item 2"
  },
  "CG_CGPSC_SSE/cg.eco.economy": {
    "doc": "CG_CGPSC_SSE",
    "where": "Paper 1 General Studies, Part 2: General Knowledge of Chhattisgarh, item 5"
  },
  "CTET/cdp.child_development.intelligence": {
    "doc": "CTET",
    "where": "Paper I, I. Child Development and Pedagogy, a) Child Development (Primary School Child)"
  },
  "DL_DSSSB_TGT/eng.comprehension": {
    "doc": "DL_DSSSB_TGT",
    "where": "Section-A: English Language & Comprehension (20 Marks)"
  },
  "GJ_GSSSB/gj.current_affairs_gj": {
    "doc": "GJ_GSSSB",
    "where": "Preliminary Exam syllabus, (3) General Awareness and Current Affairs (30 Marks), item 7, page 4"
  },
  "GJ_GSSSB/rea.coding": {
    "doc": "GJ_GSSSB",
    "where": "Preliminary Exam syllabus, (5) Reasoning (60 Marks), item 1, page 5"
  },
  "HR_TET/cdp.child_development": {
    "doc": "HR_TET",
    "where": "Annexure-I, Level-I, Part-I: Child Development and Pedagogy, item A"
  },
  "HR_TET/haryana.history": {
    "doc": "HR_TET",
    "where": "Annexure-I, Level-I, Part-III: General Studies, item A"
  },
  "JH_TET/cdp.assessment.nep": {
    "doc": "JH_TET",
    "where": "Child Development and Pedagogy, Level-1 (Classes 1-5), Part (A) Concepts, items 2 and 5; repeated for Level-2"
  },
  "KA_KARTET/lang1.sandhi": {
    "doc": "KA_KARTET",
    "where": "Kannada syllabus, Paper-1 and Paper-2: Kannada Language, Literature and Grammar, Grammar"
  },
  "KA_KCET/phy.units_measurement": {
    "doc": "KA_KCET",
    "where": "Physics syllabus, Class XI (Theory), Unit I: Units and Measurements"
  },
  "KA_KCET/math.linear_inequalities": {
    "doc": "KA_KCET",
    "where": "Mathematics syllabus, Class XI, Unit II: Algebra, 2. Linear Inequalities"
  },
  "KA_KCET/bio.biological_classification": {
    "doc": "KA_KCET",
    "where": "Biology syllabus, Class XI, I. Diversity in the Living World, Chapter-2"
  },
  "KA_KPSC_KAS/gs.current_affairs": {
    "doc": "KA_KPSC_KAS",
    "where": "Preliminary Examination (objective type), Paper-I, item (i); State current events are Paper-II, item (i)"
  },
  "KA_KPSC_KAS/csat.science_tech": {
    "doc": "KA_KPSC_KAS",
    "where": "Preliminary Examination (objective type), Paper-II, item (ii)"
  },
  "MH_MPSC_GROUP_C/gs.history": {
    "doc": "MH_MPSC_GROUP_C",
    "where": "General Ability Test (code 1122), syllabus item 1: History"
  },
  "ML_MPSC/gs.current_affairs": {
    "doc": "ML_MPSC",
    "where": "Section II, A. Preliminary Examination, Paper I, item (i)"
  },
  "MP_RAEO/horti.package": {
    "doc": "MP_RAEO",
    "where": "Chapter 4 Syllabus (single paper), Unit 7: Horticulture"
  },
  "MZ_MPSC/mz.culture.mizo_society": {
    "doc": "MZ_MPSC",
    "where": "Preliminary Examination, Paper-I: General Studies, item (h)"
  },
  "NDA/math.integral_calculus": {
    "doc": "NDA",
    "where": "Paper-I Mathematics (Code No. 01), heading 6, page 20"
  },
  "NDA/math.trigonometry": {
    "doc": "NDA",
    "where": "Paper-I Mathematics (Code No. 01), heading 3, page 20"
  },
  "NSEA/astro.phy.units_measurement": {
    "doc": "NSEA",
    "where": "Astronomy syllabus, Part 1: Physics (refers to Physics syllabus), Unit I: Units and Measurements"
  },
  "NSEA/astro.phy.kinematics": {
    "doc": "NSEA",
    "where": "Astronomy syllabus, Part 1: Physics, Unit II: Motion in a Straight Line; Unit III: Motion in a Plane"
  },
  "NSEA/astro.astro.celestial_mechanics": {
    "doc": "NSEA",
    "where": "Astronomy syllabus, Part 1: Physics, Unit VII: Gravitation"
  },
  "NSEA/astro.astro.telescopes": {
    "doc": "NSEA",
    "where": "Astronomy syllabus, Part 3: Elementary Astronomical notions"
  },
  "NSEB/bio.human_welfare": {
    "doc": "NSEB",
    "where": "Biology syllabus for NSEB and INBO, Unit VIII: Biology and Human Welfare"
  },
  "NSEC/chem.periodicity": {
    "doc": "NSEC",
    "where": "Chemistry, Unit III: Classification of Elements and Periodicity in Properties"
  },
  "NSEJS/js.chem.matter_states": {
    "doc": "NSEJS",
    "where": "Junior Science, Unit I: Matter-Nature and Behaviour (page 19)"
  },
  "NSEJS/js.chem.periodic_classification": {
    "doc": "NSEJS",
    "where": "Junior Science, Unit II: Chemical Substances - Nature and Behaviour (page 19)"
  },
  "NSEJS/js.chem.acids_bases_salts": {
    "doc": "NSEJS",
    "where": "Junior Science, Unit II: Chemical Substances - Nature and Behaviour (page 19)"
  },
  "NSTSE/math.triangles": {
    "doc": "NSTSE",
    "where": "Class 9 paper, Mathematics section; also Class 10 paper, Mathematics section (syllabus page 2)"
  },
  "RJ_RPSC_RAS/rj.culture.painting": {
    "doc": "RJ_RPSC_RAS",
    "where": "Preliminary paper, heading: History, Art, Culture, Literature, Tradition & Heritage of Rajasthan"
  },
  "RJ_RPSC_RAS/rj.polity.rj_govt": {
    "doc": "RJ_RPSC_RAS",
    "where": "Preliminary paper, heading: Political and Administrative System of Rajasthan"
  },
  "RJ_RSMSSB/lang.eng_idioms": {
    "doc": "RJ_RSMSSB",
    "where": "Para 17 syllabus, Language Knowledge, General English (page 23 of 24)"
  },
  "RRB_GROUP_D/rrbd.gs.chemistry": {
    "doc": "RRB_GROUP_D",
    "where": "Computer Based Test, Question Type and Syllabus, item c: General Science"
  },
  "SSC_CHSL/eng.synonyms": {
    "doc": "SSC_CHSL",
    "where": "Tier-I, Part I: English Language (Basic Knowledge), para 13.10.1, page 21"
  },
  "SSC_CHSL/ga.geography.india": {
    "doc": "SSC_CHSL",
    "where": "Tier-I, Part IV: General Awareness, para 13.10.4, page 22"
  },
  "SSC_GD/gd.reason.relationships": {
    "doc": "SSC_GD",
    "where": "Computer Based Examination, Part-A: General Intelligence and Reasoning, para 12.1.11.1"
  },
  "TN_TNPSC_GROUP2/tn.literature": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP2/tn.history.sangam": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP2/tn.history.archaeology": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP2/apt.simplification": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part B: Aptitude and Mental Ability, Unit I: Aptitude"
  },
  "TN_TNPSC_GROUP2/tn.history": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP4/tamil.grammar": {
    "doc": "TN_TNPSC_GROUP4",
    "where": "Part A: Tamil Eligibility-cum-Scoring Test (SSLC Standard), Unit I: Grammar (Ilakkanam), 25 questions"
  },
  "TN_TNPSC_GROUP4/tamil.grammar.eluthu": {
    "doc": "TN_TNPSC_GROUP4",
    "where": "Part A: Tamil Eligibility-cum-Scoring Test, Unit I: Grammar (Ilakkanam), sub-head Eluthu (Letters)"
  },
  "TN_TNPSC_GROUP4/tamil.grammar.sol": {
    "doc": "TN_TNPSC_GROUP4",
    "where": "Part A: Tamil Eligibility-cum-Scoring Test, Unit I: Grammar (Ilakkanam), sub-head Sol (Words)"
  },
  "TN_TNUSRB_SI/tn.gk.history": {
    "doc": "TN_TNUSRB_SI",
    "where": "Main Written Examination, Part-A: General Knowledge (page 2)"
  },
  "TS_EAMCET/bot.morphology_plants": {
    "doc": "TS_EAMCET",
    "where": "A&P Stream syllabus, Botany, topic 2: Structural Organisation in Plants - Morphology"
  },
  "TS_POLICE_SI/gs.telangana": {
    "doc": "TS_POLICE_SI",
    "where": "Preliminary Written Test syllabus (Annexure II), Part B: General Studies, Item 6"
  },
  "TS_TSPSC_GROUP1/telangana_movement.society.culture": {
    "doc": "TS_TSPSC_GROUP1",
    "where": "Preliminary Test syllabus (General Studies and Mental Ability), item 11"
  },
  "TS_TSPSC_GROUP1/telangana_movement.economy": {
    "doc": "TS_TSPSC_GROUP1",
    "where": "Main Examination Paper-IV Economy and Development, Part II: Telangana Economy"
  },
  "TS_TSPSC_GROUP1/gs.international_relations.current": {
    "doc": "TS_TSPSC_GROUP1",
    "where": "Preliminary Test syllabus (General Studies and Mental Ability), items 1 and 2"
  },
  "TS_TSPSC_GROUP1/gs.geography": {
    "doc": "TS_TSPSC_GROUP1",
    "where": "Preliminary Test syllabus (General Studies and Mental Ability), item 6"
  },
  "TS_TSPSC_GROUP1/gs.geography.indian": {
    "doc": "TS_TSPSC_GROUP1",
    "where": "Preliminary Test syllabus (General Studies and Mental Ability), item 6"
  },
  "TS_TSPSC_GROUP2/gs.economy": {
    "doc": "TS_TSPSC_GROUP2",
    "where": "Paper III: Economy and Development, Part I: Indian Economy: Issues and Challenges, Unit 5: Planning, NITI Aayog and Public Finance"
  },
  "TS_TSPSC_GROUP3/gs.social_inclusion": {
    "doc": "TS_TSPSC_GROUP3",
    "where": "Paper-I: General Studies and General Abilities, item 9"
  },
  "TS_TSPSC_GROUP3/gs.current_affairs": {
    "doc": "TS_TSPSC_GROUP3",
    "where": "Paper-I: General Studies and General Abilities, item 1"
  },
  "UK_TET/lang2.comprehension": {
    "doc": "UK_TET",
    "where": "UTET I, III. Language-II, a) Comprehension (page 2); same heading in UTET II, III. Language-II (page 5)"
  },
  "UK_TET/math.content": {
    "doc": "UK_TET",
    "where": "UTET I, IV Mathematics, a. Content (pages 2-3)"
  },
  "UK_TET/math_sci.science_content.natural_resources": {
    "doc": "UK_TET",
    "where": "UTET II, IV. Mathematics and Science, Science, a. Content (page 6)"
  },
  "UK_UKPSC_PCS/gs.geog.india": {
    "doc": "UK_UKPSC_PCS",
    "where": "Preliminary Paper I General Studies, Unit 2: Indian and World Geography"
  },
  "UK_UKPSC_PCS/gs.env.ecology": {
    "doc": "UK_UKPSC_PCS",
    "where": "Preliminary Paper I General Studies, Unit 5: General Science and Technology"
  },
  "UPSC_PRELIMS/gs.history": {
    "doc": "UPSC_PRELIMS",
    "where": "Part A: Preliminary Examination, Paper I (General Studies), page 32"
  },
  "UP_POLICE_CONSTABLE/hindi.vilom": {
    "doc": "UP_POLICE_CONSTABLE",
    "where": "Appendix-1, Part 2: General Hindi, item 2: Basic knowledge of Hindi grammar"
  },
  "UP_POLICE_CONSTABLE/gk.geography": {
    "doc": "UP_POLICE_CONSTABLE",
    "where": "Appendix-1, Part 1: General Knowledge"
  },
  "UP_POLICE_SI/hindi.varnamala": {
    "doc": "UP_POLICE_SI",
    "where": "Written Examination, Appendix-1, Section 1: General Hindi, item 2: basic knowledge of Hindi grammar"
  },
  "UP_POLICE_SI/gk.computer_basics": {
    "doc": "UP_POLICE_SI",
    "where": "Written Examination, Appendix-1, Section 2: Basic Law / Constitution / General Knowledge, general knowledge paragraph"
  },
  "UP_UPTET/lang2.comprehension": {
    "doc": "UP_UPTET",
    "where": "Paper I (Classes I to V), III. Language II, English, (a) Content"
  },
  "WB_TET/evs.pedagogy.scope_relations": {
    "doc": "WB_TET",
    "where": "Part E: Environmental Studies, (b) Pedagogical Issues"
  }
};
