// GENERATED by scripts/build-official-readings.ts — do not edit by hand.
//
// Exam patterns and syllabus places read from the conducting bodies' own
// documents, each read twice (the second reading re-opened every document).
// Only what both readings found is here. Hand-read entries live in
// src/lib/pattern-verified.ts and src/lib/official-syllabus-lines.ts and win
// over an entry of the same key here.

import type { VerifiedPattern } from "@/lib/pattern-verified";
import type { SyllabusDocument } from "@/lib/official-syllabus-lines";

export const READ_PATTERNS: Readonly<Record<string, VerifiedPattern>> = {
  "CTET": {
    "code": "CTET",
    "stage": "Paper I",
    "questions": 150,
    "marks": 150,
    "durationMin": 150,
    "negativePerWrong": 0,
    "sections": [
      {
        "name": "Child Development and Pedagogy",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Mathematics",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Environmental Studies",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language I",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Language II",
        "questions": 30,
        "marks": 30
      }
    ],
    "languages": "bilingual (Hindi/English); Language I and II in the two languages the candidate chooses",
    "source": {
      "url": "https://cdnbbsr.s3waas.gov.in/s3443dec3062d0286986e21dc0631734c9/uploads/2026/05/202605111250310617.pdf",
      "publisher": "Central Board of Secondary Education (CBSE), Central Teacher Eligibility Test Unit",
      "publisherShort": "CBSE",
      "title": "Information Bulletin, CTET-September, 2026 (22nd Edition)",
      "publishedOn": "",
      "para": "Para 7, Structure and Content of CTET, printed Page 3 (PDF page 9)"
    },
    "checkedOn": "2026-09-29"
  },
  "GJ_GSSSB": {
    "code": "GJ_GSSSB",
    "stage": "Stage 1: Preliminary Examination",
    "questions": 150,
    "marks": 150,
    "durationMin": 120,
    "negativePerWrong": 0.25,
    "sections": [
      {
        "name": "English",
        "questions": null,
        "marks": 15
      },
      {
        "name": "Gujarati",
        "questions": null,
        "marks": 15
      },
      {
        "name": "General Awareness and Current Affairs",
        "questions": null,
        "marks": 30
      },
      {
        "name": "Quantitative Aptitude",
        "questions": null,
        "marks": 30
      },
      {
        "name": "Reasoning",
        "questions": null,
        "marks": 60
      }
    ],
    "languages": "",
    "source": {
      "url": "https://gsssb.gujarat.gov.in/ViewFile?fileName=%E2%9C%BFAv%E2%9C%BFyIFCoiJ6Y3lYByFvHVh8MmeAii5ssTgCCOkn8KmVJNxP3BgxiaCc0G%E2%9C%BFstEl6shK6HWh9Q%E2%9C%BFVe3BGNJvWqxGImhue0J29cbFsjZAobnnoZxQtkq8xRLKWeO%E2%9C%BF1wlObiOQzXmh8KZl8wrFETGcWORA%E2%99%AC%E2%99%AC",
      "publisher": "Gujarat Subordinate Service Selection Board (ગુજરાત ગૌણ સેવા પસંદગી મંડળ), Gandhinagar",
      "publisherShort": "GSSSB",
      "title": "Advt. No. 378/202526 - Gujarat Subordinate Services, Class III (Group-A and Group-B) Combined Competitive Examination -…",
      "publishedOn": "2026-02-03",
      "para": "Para 21 'Examination method', Stage 1, pages 32-33 of 44 of the advertisement dated 03/02/2026",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29"
  },
  "IBPS_CLERK": {
    "code": "IBPS_CLERK",
    "stage": "Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0,
    "negativeText": "one fourth (0.25) of the marks assigned to a question is deducted for each wrong answer",
    "sections": [
      {
        "name": "English Language",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Numerical Ability",
        "questions": 35,
        "marks": 35
      },
      {
        "name": "Reasoning Ability",
        "questions": 35,
        "marks": 35
      }
    ],
    "languages": "English Language test in English; the other two tests in English, Hindi and, in some States/UTs, a regional language",
    "source": {
      "url": "https://www.ibps.in/wp-content/uploads/Notification_CRP_CSA_XVI-Final.pdf",
      "publisher": "Institute of Banking Personnel Selection",
      "publisherShort": "IBPS",
      "title": "Notification: CRP CSA-XVI, Common Recruitment Process for Recruitment of Customer Service Associates (CSA) in…",
      "publishedOn": "2026-08-01",
      "para": "Clause D (Structure of Examination), I(a), printed page 14 (PDF page 17)"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "MH_MPSC_GROUP_C": {
    "code": "MH_MPSC_GROUP_C",
    "stage": "Combined Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0.25,
    "sections": [
      {
        "name": "General Ability Test (subject code 1122)",
        "questions": 100,
        "marks": 100
      }
    ],
    "languages": "Marathi and English",
    "source": {
      "url": "https://mpsc.gov.in/examination_scheme/17",
      "publisher": "Maharashtra Public Service Commission",
      "publisherShort": "MPSC",
      "title": "Maharashtra Group C Services Combined Examination - Revised Scheme of Examination",
      "publishedOn": "2026-05-20",
      "para": "Revised Scheme of Examination dated 20 May 2026, para 6.1.1 (table), page 7 of 10",
      "scanned": true
    },
    "checkedOn": "2026-09-29"
  },
  "ML_MPSC": {
    "code": "ML_MPSC",
    "stage": "Preliminary Examination, Paper I",
    "questions": 100,
    "marks": 200,
    "durationMin": 120,
    "negativePerWrong": 0,
    "sections": [],
    "languages": "",
    "source": {
      "url": "https://mpsc.meghalaya.gov.in/syllabus/MCS_Syllabus2025.pdf",
      "publisher": "Meghalaya Public Service Commission",
      "publisherShort": "MPSC",
      "title": "Government of Meghalaya, Personnel & A.R. (A) Department, Notification No. PER.6/97/225 - syllabus and pattern of…",
      "publishedOn": "2025-08-11",
      "para": "Marks, duration, objective type: Section II, A. Preliminary Examination, paras (1)-(4) I, page 1 of 3 of…"
    },
    "checkedOn": "2026-09-29"
  },
  "SBI_CLERK": {
    "code": "SBI_CLERK",
    "stage": "Phase-I: Preliminary Examination",
    "questions": 100,
    "marks": 100,
    "durationMin": 60,
    "negativePerWrong": 0,
    "negativeText": "1/4th of the mark assigned to a question is deducted for each wrong answer",
    "sections": [
      {
        "name": "English language",
        "questions": 30,
        "marks": 30
      },
      {
        "name": "Numerical Ability",
        "questions": 35,
        "marks": 35
      },
      {
        "name": "Reasoning Ability",
        "questions": 35,
        "marks": 35
      }
    ],
    "languages": "English Language test in English; the other two tests in English, Hindi and, in some States/UTs, a regional language",
    "source": {
      "url": "https://sbi.bank.in/webfiles/uploads/files_2627/08/JA_2026_Detailed_Advt_Eng.pdf",
      "publisher": "State Bank of India",
      "publisherShort": "SBI",
      "title": "Recruitment of Junior Associates (Customer Support & Sales) - Advertisement No. CRPD/CR/2026-27/17",
      "publishedOn": "2026-08-11",
      "para": "Advertisement para 4 'Selection Procedure', Phase-I: Preliminary Examination, page 5 of 11",
      "kind": "advertisement"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  },
  "TN_TNPSC_GROUP2": {
    "code": "TN_TNPSC_GROUP2",
    "stage": "Preliminary Examination",
    "questions": 200,
    "marks": 300,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "negativeText": "no deduction printed for a wrong answer; 0.5 mark is deducted if a question is left blank",
    "sections": [
      {
        "name": "A. General Studies (Degree Standard)",
        "questions": 75,
        "marks": null
      },
      {
        "name": "B. Aptitude and Mental Ability (SSLC Standard)",
        "questions": 25,
        "marks": null
      },
      {
        "name": "C. Language (General Tamil or General English) (SSLC Standard)",
        "questions": 100,
        "marks": null
      }
    ],
    "languages": "General Studies in Tamil and English; the language part is General Tamil or General English",
    "source": {
      "url": "https://tnpsc.gov.in/document/english/07_2026%20Dated_11.08.2026%20English%20version.pdf",
      "publisher": "Tamil Nadu Public Service Commission",
      "publisherShort": "TNPSC",
      "title": "Combined Civil Services Examination - II (Group II and IIA Services) - Notification No. 07/2026 (Advertisement No. 740)",
      "publishedOn": "2026-08-11",
      "para": "Para 6.1 Preliminary Examination (Single Paper), Scheme of Examination table, page 19 of 87"
    },
    "checkedOn": "2026-09-29"
  },
  "TN_TNPSC_GROUP4": {
    "code": "TN_TNPSC_GROUP4",
    "stage": "Written Examination",
    "questions": 200,
    "marks": 300,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "negativeText": "no deduction printed for a wrong answer; 0.5 mark is deducted if a question is left blank",
    "marksNote": "Part A has 100 questions for 150 marks; Parts B and C (75 + 25 questions) share one maximum of 150",
    "sections": [
      {
        "name": "Part A: Tamil Eligibility-cum-Scoring Test (SSLC Standard)",
        "questions": 100,
        "marks": 150
      },
      {
        "name": "Part B: General Studies (SSLC Standard)",
        "questions": 75,
        "marks": null
      },
      {
        "name": "Part C: Aptitude and Mental Ability (SSLC Standard)",
        "questions": 25,
        "marks": null
      }
    ],
    "languages": "Part A (Tamil Eligibility-cum-Scoring Test) set in Tamil only; Part B and Part C set both in Tamil and English",
    "source": {
      "url": "https://tnpsc.gov.in/document/english/Grp%20IV%20English_.pdf",
      "publisher": "Tamil Nadu Public Service Commission",
      "publisherShort": "TNPSC",
      "title": "Combined Civil Services Examination - IV (Group IV Services) - Notification No. 07/2025 (Advertisement No.709), read…",
      "publishedOn": "2025-04-25",
      "para": "Para 6 Scheme of Examination (table) and para 6.1, page 19 of 72"
    },
    "checkedOn": "2026-09-29"
  },
  "TN_TNUSRB_SI": {
    "code": "TN_TNUSRB_SI",
    "stage": "Main Written Examination",
    "questions": 140,
    "marks": 70,
    "durationMin": 150,
    "negativePerWrong": 0,
    "negativeNotPrinted": true,
    "sections": [
      {
        "name": "Part-A - General Knowledge",
        "questions": 80,
        "marks": 40
      },
      {
        "name": "Part-B - Psychology Test",
        "questions": 60,
        "marks": 30
      }
    ],
    "languages": "",
    "source": {
      "url": "https://tnusrb.tn.gov.in/pdfs/SI(TK,%20AR)%202025%20Notification_n.pdf",
      "publisher": "Tamil Nadu Uniformed Services Recruitment Board",
      "publisherShort": "TNUSRB",
      "title": "Notification No: 01/2025 - Direct Recruitment for the posts of Sub-Inspectors of Police - 2025 [Taluk & Armed Reserve…",
      "publishedOn": "2025-04-04",
      "para": "Notification No. 01/2025, para 16 (A) Written Examination, Part-II Main Written Examination, items i-v, page…"
    },
    "checkedOn": "2026-09-29"
  },
  "TS_POLICE_PC": {
    "code": "TS_POLICE_PC",
    "stage": "Preliminary Written Test",
    "questions": 200,
    "marks": 200,
    "durationMin": 180,
    "negativePerWrong": 0,
    "negativeText": "a wrong answer, or more than one bubble darkened, is marked minus 20% of the question's full marks; a question left blank gets zero",
    "sections": [],
    "languages": "English-Telugu and English-Urdu versions",
    "source": {
      "url": "https://doc.tgprb.in/PC+(Civil+et+al)+2026+Notification+dated+29-07-2026.pdf",
      "publisher": "Telangana State Level Police Recruitment Board",
      "publisherShort": "TSLPRB",
      "title": "Notification Rc No. 189 / Rect. / Rect.2 / 2026 - SCT Police Constable (Civil) and / or equivalent Posts",
      "publishedOn": "2026-07-29",
      "para": "Para 16 (Selection Procedure / Scheme), sub-para A, page 25 of 57"
    },
    "checkedOn": "2026-09-29",
    "negativeNotPrinted": true
  }
};

export const READ_DOCUMENTS: Readonly<Record<string, SyllabusDocument>> = {
  "AP_APPSC_GROUP1": {
    "publisherShort": "APPSC",
    "name": "Annexure to Brief Notification No.07/2026: Scheme and Syllabus for Recruitment to the Posts falling under…",
    "url": "https://psc.ap.gov.in/Documents/NotificationDocuments/Group_I_072026.pdf",
    "readOn": "2026-09-29"
  },
  "CDS": {
    "publisherShort": "UPSC",
    "name": "Appendix-I, Part B 'Standard and Syllabus of the Examination' in Examination Notice No. 11/2026-CDS-II",
    "url": "https://www.upsc.gov.in/sites/default/files/Notif-CDS-II-2026-Engl-200526.pdf",
    "readOn": "2026-09-29",
    "caveat": "The syllabus is printed inside the examination notice."
  },
  "CTET": {
    "publisherShort": "CBSE",
    "name": "Appendix-I, Structure and Content of Syllabus (Paper I and Paper II), in the Information Bulletin…",
    "url": "https://cdnbbsr.s3waas.gov.in/s3443dec3062d0286986e21dc0631734c9/uploads/2026/05/202605111250310617.pdf",
    "readOn": "2026-09-29"
  },
  "GJ_GSSSB": {
    "publisherShort": "GSSSB",
    "name": "Advt. 378/202526 - Combined Competitive Examination, Stage 1: Preliminary Exam detailed syllabus",
    "url": "https://gsssb.gujarat.gov.in/ViewFile?fileName=4naZ%E2%9C%BF8wS64TzwZ61AZrbMP4tvDBt3Mj8UPSd1xKcshtZxTB5t5ltTF2mrczYtutOJGDlDeTKGm0IBe3QAs0YsAvhcBHVUA7rWLv6ae41Hda0d6MmkmlJGOJcCYvEzD6nnekULO9MvmUb8i9F7qJMxg%E2%99%AC%E2%99%AC",
    "readOn": "2026-09-29"
  },
  "KA_KPSC_KAS": {
    "publisherShort": "KPSC",
    "name": "Syllabus for Gazetted Probationers Exam",
    "url": "https://kpsc.kar.nic.in/syll_GP.pdf",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "MH_MPSC_GROUP_C": {
    "publisherShort": "MPSC",
    "name": "Maharashtra Group-C Services Combined Preliminary Examination - Syllabus",
    "url": "https://mpsc.gov.in/examination_syllabus/18",
    "readOn": "2026-09-29",
    "scanned": true
  },
  "ML_MPSC": {
    "publisherShort": "MPSC",
    "name": "Syllabus for the Meghalaya Civil Service - Notification No. PER.6/97/225 dated 11 August 2025, Section II A",
    "url": "https://mpsc.meghalaya.gov.in/syllabus/MCS_Syllabus2025.pdf",
    "readOn": "2026-09-29"
  },
  "NDA": {
    "publisherShort": "UPSC",
    "name": "Appendix-I, Part B 'Syllabus of the Examination' in Examination Notice No. 10/2026-NDA-II",
    "url": "https://www.upsc.gov.in/sites/default/files/Notif-NDA-II-2026-Engl-200526.pdf",
    "readOn": "2026-09-29",
    "caveat": "The syllabus is printed inside the examination notice."
  },
  "NSEJS": {
    "publisherShort": "IAPT",
    "name": "Syllabus for National Standard Examination and Indian National Olympiad in Physics, Chemistry, Biology,…",
    "url": "https://iapt.org.in/wp-content/uploads/images/syllabus-for-nse-ino-2022-2023.pdf",
    "readOn": "2026-09-29",
    "caveat": "The file is titled 2022-2023; IAPT's site links it as the syllabus for NSE 2026-27."
  },
  "SSC_GD": {
    "publisherShort": "SSC",
    "name": "Indicative syllabus, para 12.1.11 of the Notice of Constable (GD) in CAPFs and SSF, and Rifleman (GD) in…",
    "url": "https://ssc.gov.in/api/attachment/uploads/masterData/NoticeBoards/Notice_of_CTGD_2026.pdf",
    "readOn": "2026-09-29"
  },
  "TN_TNPSC_GROUP2": {
    "publisherShort": "TNPSC",
    "name": "Combined Civil Services (Preliminary) Examination - II (Group II and IIA Services) - Syllabus, Code: 495",
    "url": "https://tnpsc.gov.in/static_pdf/syllabus/495_Group%20II%20and%20IIA%20prelims.pdf",
    "readOn": "2026-09-29"
  },
  "TN_TNPSC_GROUP4": {
    "publisherShort": "TNPSC",
    "name": "Annexure III - Syllabus (Code: 496) of Notification No.07/2025, pages 55 to 58 of 72",
    "url": "https://tnpsc.gov.in/document/english/Grp%20IV%20English_.pdf",
    "readOn": "2026-09-29"
  },
  "TN_TNUSRB_SI": {
    "publisherShort": "TNUSRB",
    "name": "Syllabus for Written Examination - Sub-Inspectors of Police (Taluk & AR) - 2025",
    "url": "https://tnusrb.tn.gov.in/pdfs/SI_2025_Syllabus.pdf",
    "readOn": "2026-09-29"
  },
  "UK_TET": {
    "publisherShort": "UBSE",
    "name": "Structure and Content of Syllabus - UTET I (classes I to V) and UTET II (classes VI to VIII), listed by the…",
    "url": "https://cdnbbsr.s3waas.gov.in/s32dbf21633f03afcf882eaf10e4b5caca/uploads/2025/07/202507111495469767.pdf",
    "readOn": "2026-09-29",
    "scanned": true,
    "caveat": "The pages print no date; UBSE's site lists them for UTET."
  }
};

/** "{EXAM}/{topic.code}" → the document's key and the place in it. */
export const READ_PLACES: Readonly<Record<string, { doc: string; where: string }>> = {
  "AP_APPSC_GROUP1/mental_ability.logical_reasoning.series": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 2 (page 9)"
  },
  "AP_APPSC_GROUP1/mental_ability.data_interpretation": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 15 (page 9)"
  },
  "AP_APPSC_GROUP1/mental_ability.logical_reasoning": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 1 (page 9)"
  },
  "AP_APPSC_GROUP1/quant.time_work": {
    "doc": "AP_APPSC_GROUP1",
    "where": "Screening Test Paper II General Aptitude, Part (A) General Mental and Psychological Abilities, item 11 (page 9)"
  },
  "CDS/math.geometry": {
    "doc": "CDS",
    "where": "Elementary Mathematics (Code No. 13), heading Geometry, page 20"
  },
  "CTET/cdp.child_development.intelligence": {
    "doc": "CTET",
    "where": "Paper I, I. Child Development and Pedagogy, a) Child Development (Primary School Child)"
  },
  "GJ_GSSSB/gj.current_affairs_gj": {
    "doc": "GJ_GSSSB",
    "where": "Preliminary Exam syllabus, (3) General Awareness and Current Affairs (30 Marks), item 7, page 4"
  },
  "GJ_GSSSB/rea.coding": {
    "doc": "GJ_GSSSB",
    "where": "Preliminary Exam syllabus, (5) Reasoning (60 Marks), item 1, page 5"
  },
  "KA_KPSC_KAS/gs.current_affairs": {
    "doc": "KA_KPSC_KAS",
    "where": "Preliminary Examination (objective type), Paper-I, item (i); State current events are Paper-II, item (i)"
  },
  "KA_KPSC_KAS/csat.science_tech": {
    "doc": "KA_KPSC_KAS",
    "where": "Preliminary Examination (objective type), Paper-II, item (ii)"
  },
  "MH_MPSC_GROUP_C/gs.history": {
    "doc": "MH_MPSC_GROUP_C",
    "where": "General Ability Test (code 1122), syllabus item 1: History"
  },
  "ML_MPSC/gs.current_affairs": {
    "doc": "ML_MPSC",
    "where": "Section II, A. Preliminary Examination, Paper I, item (i)"
  },
  "NDA/math.integral_calculus": {
    "doc": "NDA",
    "where": "Paper-I Mathematics (Code No. 01), heading 6, page 20"
  },
  "NDA/math.trigonometry": {
    "doc": "NDA",
    "where": "Paper-I Mathematics (Code No. 01), heading 3, page 20"
  },
  "NSEJS/js.chem.matter_states": {
    "doc": "NSEJS",
    "where": "Junior Science, Unit I: Matter-Nature and Behaviour (page 19)"
  },
  "NSEJS/js.chem.periodic_classification": {
    "doc": "NSEJS",
    "where": "Junior Science, Unit II: Chemical Substances - Nature and Behaviour (page 19)"
  },
  "NSEJS/js.chem.acids_bases_salts": {
    "doc": "NSEJS",
    "where": "Junior Science, Unit II: Chemical Substances - Nature and Behaviour (page 19)"
  },
  "SSC_GD/gd.reason.relationships": {
    "doc": "SSC_GD",
    "where": "Computer Based Examination, Part-A: General Intelligence and Reasoning, para 12.1.11.1"
  },
  "TN_TNPSC_GROUP2/tn.literature": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP2/tn.history.sangam": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP2/tn.history.archaeology": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP2/apt.simplification": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part B: Aptitude and Mental Ability, Unit I: Aptitude"
  },
  "TN_TNPSC_GROUP2/tn.history": {
    "doc": "TN_TNPSC_GROUP2",
    "where": "Part A: General Studies, Unit VI: History, Culture, Heritage, and Socio-Political Movements in Tamil Nadu"
  },
  "TN_TNPSC_GROUP4/tamil.grammar": {
    "doc": "TN_TNPSC_GROUP4",
    "where": "Part A: Tamil Eligibility-cum-Scoring Test (SSLC Standard), Unit I: Grammar (Ilakkanam), 25 questions"
  },
  "TN_TNPSC_GROUP4/tamil.grammar.eluthu": {
    "doc": "TN_TNPSC_GROUP4",
    "where": "Part A: Tamil Eligibility-cum-Scoring Test, Unit I: Grammar (Ilakkanam), sub-head Eluthu (Letters)"
  },
  "TN_TNPSC_GROUP4/tamil.grammar.sol": {
    "doc": "TN_TNPSC_GROUP4",
    "where": "Part A: Tamil Eligibility-cum-Scoring Test, Unit I: Grammar (Ilakkanam), sub-head Sol (Words)"
  },
  "TN_TNUSRB_SI/tn.gk.history": {
    "doc": "TN_TNUSRB_SI",
    "where": "Main Written Examination, Part-A: General Knowledge (page 2)"
  },
  "UK_TET/lang2.comprehension": {
    "doc": "UK_TET",
    "where": "UTET I, III. Language-II, a) Comprehension (page 2); same heading in UTET II, III. Language-II (page 5)"
  },
  "UK_TET/math.content": {
    "doc": "UK_TET",
    "where": "UTET I, IV Mathematics, a. Content (pages 2-3)"
  },
  "UK_TET/math_sci.science_content.natural_resources": {
    "doc": "UK_TET",
    "where": "UTET II, IV. Mathematics and Science, Science, a. Content (page 6)"
  }
};
